# ── Stage 1: build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

# Build-time env vars — baked into the JS bundle by Vite's loadEnv.
# Pass these via --build-arg or docker-compose build.args.
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_ASSETS_URL
ARG NEXT_PUBLIC_CLIENT_URL
ARG NEXT_PUBLIC_DEPLOY_ENV=production
ARG NEXT_PUBLIC_BYPASS_DOMAIN_CHECK
ARG NEXT_PUBLIC_AI_WS_URL
ARG NEXT_PUBLIC_FEATURE_SSO_ENABLED
ARG NEXT_PUBLIC_FEATURE_ENABLE_DEMO_TEST_CASES
ARG NEXT_PUBLIC_FIGMA_CLIENT_ID
ARG NEXT_PUBLIC_FIGMA_CLIENT_SECRET
ARG NEXT_PUBLIC_FIGMA_REDIRECT_URI
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS_ID

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_ASSETS_URL=$NEXT_PUBLIC_ASSETS_URL \
    NEXT_PUBLIC_CLIENT_URL=$NEXT_PUBLIC_CLIENT_URL \
    NEXT_PUBLIC_DEPLOY_ENV=$NEXT_PUBLIC_DEPLOY_ENV \
    NEXT_PUBLIC_BYPASS_DOMAIN_CHECK=$NEXT_PUBLIC_BYPASS_DOMAIN_CHECK \
    NEXT_PUBLIC_AI_WS_URL=$NEXT_PUBLIC_AI_WS_URL \
    NEXT_PUBLIC_FEATURE_SSO_ENABLED=$NEXT_PUBLIC_FEATURE_SSO_ENABLED \
    NEXT_PUBLIC_FEATURE_ENABLE_DEMO_TEST_CASES=$NEXT_PUBLIC_FEATURE_ENABLE_DEMO_TEST_CASES \
    NEXT_PUBLIC_FIGMA_CLIENT_ID=$NEXT_PUBLIC_FIGMA_CLIENT_ID \
    NEXT_PUBLIC_FIGMA_CLIENT_SECRET=$NEXT_PUBLIC_FIGMA_CLIENT_SECRET \
    NEXT_PUBLIC_FIGMA_REDIRECT_URI=$NEXT_PUBLIC_FIGMA_REDIRECT_URI \
    NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$NEXT_PUBLIC_GOOGLE_ANALYTICS_ID

COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npm run build

# ── Stage 2: serve ────────────────────────────────────────────────────────────
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
