import type {
  Artifact,
  Dataset,
  Decision,
  Deployment,
  Evaluation,
  Experiment,
  Finding,
  Model,
  ModelVersion,
  Run,
} from '../types'

export const mockModels: Model[] = [
  {
    id: 'video-recs',
    name: 'Video Recommendations',
    description:
      'Picks the next videos to show on the home feed and up-next rail.',
    owner: 'Maya Patel',
    status: 'active',
    domain: 'Recommendations',
    problemType: 'ranking',
    tags: ['home-feed', 'watch-time', 'personalization'],
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-06-18T14:30:00Z',
    productionVersionId: 'video-recs-v2',
  },
  {
    id: 'product-recs',
    name: 'Product Recommendations',
    description:
      'Recommends products shoppers are likely to buy across store and cart pages.',
    owner: 'Arjun Rao',
    status: 'active',
    domain: 'Shopping',
    problemType: 'ranking',
    tags: ['shopping', 'add-to-cart', 'personalization'],
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-06-12T11:00:00Z',
    productionVersionId: 'product-recs-v2',
  },
  {
    id: 'chat-assistant',
    name: 'Support Chat Assistant',
    description:
      'Answers customer questions in the help center chat and resolves common issues.',
    owner: 'Priya Nair',
    status: 'active',
    domain: 'Customer Support',
    problemType: 'generation',
    tags: ['chatbot', 'support', 'llm'],
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-06-20T16:20:00Z',
    productionVersionId: 'chat-assistant-v2',
  },
  {
    id: 'spam-filter',
    name: 'Email Spam Filter',
    description: 'Flags spam and phishing emails before they reach the inbox.',
    owner: 'Devon Clarke',
    status: 'active',
    domain: 'Trust & Safety',
    problemType: 'classification',
    tags: ['email', 'spam', 'phishing'],
    createdAt: '2025-12-05T09:00:00Z',
    updatedAt: '2026-05-28T10:00:00Z',
    productionVersionId: 'spam-filter-v2',
  },
  {
    id: 'content-mod',
    name: 'Content Moderation',
    description:
      'Detects harmful or policy-violating posts, comments, and images.',
    owner: 'Sofia Alvarez',
    status: 'active',
    domain: 'Trust & Safety',
    problemType: 'classification',
    tags: ['moderation', 'safety', 'multimodal'],
    createdAt: '2026-01-08T09:00:00Z',
    updatedAt: '2026-06-05T13:00:00Z',
    productionVersionId: 'content-mod-v2',
  },
  {
    id: 'auto-captions',
    name: 'Auto-Captions',
    description:
      'Generates live captions and subtitles from speech in videos and calls.',
    owner: 'Liam Nguyen',
    status: 'active',
    domain: 'Speech',
    problemType: 'other',
    tags: ['speech-to-text', 'captions', 'accessibility'],
    createdAt: '2026-02-12T09:00:00Z',
    updatedAt: '2026-06-15T09:30:00Z',
    productionVersionId: 'auto-captions-v2',
  },
  {
    id: 'photo-search',
    name: 'Photo Search',
    description:
      'Finds photos by a text description or a similar example image.',
    owner: 'Hannah Kim',
    status: 'active',
    domain: 'Search',
    problemType: 'embedding',
    tags: ['image-search', 'embeddings', 'multimodal'],
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-06-10T15:00:00Z',
    productionVersionId: 'photo-search-v2',
  },
]

export const mockVersions: ModelVersion[] = [
  {
    id: 'video-recs-v2',
    modelId: 'video-recs',
    version: 'v2.0.0',
    displayName: 'Video Recs v2',
    description:
      'Adds watch-history and session context to rank the next video.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Personalized ranking lifted click-through rate 9% and average watch time 12%.',
    createdAt: '2026-04-20T09:00:00Z',
    releasedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'video-recs-v1',
    modelId: 'video-recs',
    version: 'v1.0.0',
    displayName: 'Video Recs v1',
    description: 'First personalized feed replacing the most-popular ordering.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'Baseline personalized feed built on watch history.',
    createdAt: '2026-01-20T09:00:00Z',
    releasedAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'product-recs-v2',
    modelId: 'product-recs',
    version: 'v2.0.0',
    displayName: 'Product Recs v2',
    description:
      'Cart-aware ranking that reacts to what is already in the basket.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Cart signals raised add-to-cart rate 7% and revenue per visit 5%.',
    createdAt: '2026-04-15T09:00:00Z',
    releasedAt: '2026-04-28T09:00:00Z',
  },
  {
    id: 'product-recs-v1',
    modelId: 'product-recs',
    version: 'v1.0.0',
    displayName: 'Product Recs v1',
    description: 'Personalized product feed replacing best-seller ordering.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'First personalized product ranker on purchase history.',
    createdAt: '2026-01-25T09:00:00Z',
    releasedAt: '2026-02-08T09:00:00Z',
  },
  {
    id: 'chat-assistant-v2',
    modelId: 'chat-assistant',
    version: 'v2.0.0',
    displayName: 'Support Assistant v2',
    description:
      'Grounds answers in help-center articles so replies cite real docs.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Retrieval grounding raised resolution rate to 68% and cut wrong answers.',
    createdAt: '2026-05-05T09:00:00Z',
    releasedAt: '2026-05-18T09:00:00Z',
  },
  {
    id: 'chat-assistant-v1',
    modelId: 'chat-assistant',
    version: 'v1.0.0',
    displayName: 'Support Assistant v1',
    description:
      'First support chatbot answering from a fixed instruction set.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'Baseline assistant without document retrieval.',
    createdAt: '2026-02-10T09:00:00Z',
    releasedAt: '2026-02-22T09:00:00Z',
  },
  {
    id: 'spam-filter-v2',
    modelId: 'spam-filter',
    version: 'v2.0.0',
    displayName: 'Spam Filter v2',
    description: 'Adds phishing-link and sender-reputation features.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Phishing recall up 14 points while false positives dropped below 0.3%.',
    createdAt: '2026-04-01T09:00:00Z',
    releasedAt: '2026-04-14T09:00:00Z',
  },
  {
    id: 'spam-filter-v1',
    modelId: 'spam-filter',
    version: 'v1.0.0',
    displayName: 'Spam Filter v1',
    description: 'First learned spam classifier replacing hand-written rules.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'Baseline text classifier on email body and subject.',
    createdAt: '2025-12-15T09:00:00Z',
    releasedAt: '2025-12-28T09:00:00Z',
  },
  {
    id: 'content-mod-v2',
    modelId: 'content-mod',
    version: 'v2.0.0',
    displayName: 'Content Moderation v2',
    description: 'Reviews both text and attached images in a single model.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Image + text model raised recall to 0.91 with fewer false removals.',
    createdAt: '2026-04-22T09:00:00Z',
    releasedAt: '2026-05-06T09:00:00Z',
  },
  {
    id: 'content-mod-v1',
    modelId: 'content-mod',
    version: 'v1.0.0',
    displayName: 'Content Moderation v1',
    description: 'First automated review covering text posts and comments.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'Baseline text-only moderation classifier.',
    createdAt: '2026-01-18T09:00:00Z',
    releasedAt: '2026-01-30T09:00:00Z',
  },
  {
    id: 'auto-captions-v2',
    modelId: 'auto-captions',
    version: 'v2.0.0',
    displayName: 'Auto-Captions v2',
    description: 'Robust to background noise and overlapping speakers.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Noise-augmented training cut word error rate from 9.4% to 6.1%.',
    createdAt: '2026-05-01T09:00:00Z',
    releasedAt: '2026-05-14T09:00:00Z',
  },
  {
    id: 'auto-captions-v1',
    modelId: 'auto-captions',
    version: 'v1.0.0',
    displayName: 'Auto-Captions v1',
    description: 'First live caption model for clean studio audio.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'Baseline speech-to-text on clean recordings.',
    createdAt: '2026-02-22T09:00:00Z',
    releasedAt: '2026-03-06T09:00:00Z',
  },
  {
    id: 'photo-search-v2',
    modelId: 'photo-search',
    version: 'v2.0.0',
    displayName: 'Photo Search v2',
    description:
      'Search photos by typing a description, not just similar images.',
    status: 'released',
    stage: 'production',
    releaseNotes:
      'Text-to-image search reached recall@5 of 0.82 at 22ms lookups.',
    createdAt: '2026-04-26T09:00:00Z',
    releasedAt: '2026-05-09T09:00:00Z',
  },
  {
    id: 'photo-search-v1',
    modelId: 'photo-search',
    version: 'v1.0.0',
    displayName: 'Photo Search v1',
    description: 'First similar-photo search from an example image.',
    status: 'deprecated',
    stage: 'retired',
    releaseNotes: 'Baseline image-to-image similarity search.',
    createdAt: '2026-02-28T09:00:00Z',
    releasedAt: '2026-03-12T09:00:00Z',
  },
]

function series(base: number, delta: number, noise: number) {
  return Array.from({ length: 20 }, (_, step) => ({
    step: step + 1,
    value: Number((base + delta * step + Math.sin(step) * noise).toFixed(4)),
  }))
}

export const mockExperiments: Experiment[] = [
  {
    id: 'exp-vr-v2',
    modelId: 'video-recs',
    versionId: 'video-recs-v2',
    name: 'Watch-history personalization',
    description:
      'Test whether adding recent watch history improves the next-video ranking.',
    goal: 'Lift click-through rate and average watch time on the home feed.',
    hypothesis:
      'Ranking with recent watch history raises click-through rate by at least 8%.',
    owner: 'Maya Patel',
    status: 'concluded',
    startedAt: '2026-04-01T09:00:00Z',
    endedAt: '2026-04-18T09:00:00Z',
  },
  {
    id: 'exp-vr-v1',
    modelId: 'video-recs',
    versionId: 'video-recs-v1',
    name: 'Personalized feed launch',
    description:
      'Compare a personalized feed against the most-popular ordering.',
    goal: 'Beat the popularity baseline on click-through rate.',
    hypothesis:
      'Personalization outperforms showing the most popular videos to everyone.',
    owner: 'Maya Patel',
    status: 'concluded',
    startedAt: '2026-01-10T09:00:00Z',
    endedAt: '2026-01-26T09:00:00Z',
  },
  {
    id: 'exp-pr-v2',
    modelId: 'product-recs',
    versionId: 'product-recs-v2',
    name: 'Cart-aware recommendations',
    description:
      'React to items already in the cart when ranking product suggestions.',
    goal: 'Increase add-to-cart rate and revenue per visit.',
    hypothesis:
      'Using cart contents as context raises add-to-cart rate by at least 5%.',
    owner: 'Arjun Rao',
    status: 'concluded',
    startedAt: '2026-03-28T09:00:00Z',
    endedAt: '2026-04-12T09:00:00Z',
  },
  {
    id: 'exp-pr-v1',
    modelId: 'product-recs',
    versionId: 'product-recs-v1',
    name: 'Personalized product feed',
    description: 'Replace best-seller ordering with a purchase-history ranker.',
    goal: 'Beat the best-seller baseline on add-to-cart rate.',
    hypothesis:
      'Personalizing by purchase history beats showing everyone the best sellers.',
    owner: 'Arjun Rao',
    status: 'concluded',
    startedAt: '2026-01-15T09:00:00Z',
    endedAt: '2026-01-31T09:00:00Z',
  },
  {
    id: 'exp-ca-v2',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v2',
    name: 'Retrieval-grounded answers',
    description:
      'Let the assistant pull help-center articles before answering.',
    goal: 'Improve resolution rate and reduce incorrect answers.',
    hypothesis:
      'Grounding replies in retrieved docs raises resolution rate above 65%.',
    owner: 'Priya Nair',
    status: 'concluded',
    startedAt: '2026-04-25T09:00:00Z',
    endedAt: '2026-05-12T09:00:00Z',
  },
  {
    id: 'exp-ca-v1',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v1',
    name: 'First support assistant',
    description: 'Build a support chatbot from a fixed instruction prompt.',
    goal: 'Deflect common questions from human agents.',
    hypothesis:
      'A prompted assistant can resolve at least half of routine questions.',
    owner: 'Priya Nair',
    status: 'concluded',
    startedAt: '2026-02-01T09:00:00Z',
    endedAt: '2026-02-16T09:00:00Z',
  },
  {
    id: 'exp-sf-v2',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v2',
    name: 'Phishing detection upgrade',
    description:
      'Add phishing-link and sender-reputation features to the classifier.',
    goal: 'Catch more phishing without raising false positives.',
    hypothesis: 'Link and sender features raise phishing recall by 10+ points.',
    owner: 'Devon Clarke',
    status: 'concluded',
    startedAt: '2026-03-20T09:00:00Z',
    endedAt: '2026-04-03T09:00:00Z',
  },
  {
    id: 'exp-sf-v1',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v1',
    name: 'Spam classifier launch',
    description: 'Replace hand-written spam rules with a learned classifier.',
    goal: 'Beat the rule-based filter on accuracy and false positives.',
    hypothesis:
      'A learned classifier beats hand-written rules on overall accuracy.',
    owner: 'Devon Clarke',
    status: 'concluded',
    startedAt: '2025-12-05T09:00:00Z',
    endedAt: '2025-12-19T09:00:00Z',
  },
  {
    id: 'exp-cm-v2',
    modelId: 'content-mod',
    versionId: 'content-mod-v2',
    name: 'Image + text moderation',
    description:
      'Review attached images alongside text in a single moderation model.',
    goal: 'Catch policy violations hidden in images while keeping precision.',
    hypothesis:
      'A multimodal model raises recall on image-based violations by 12+ points.',
    owner: 'Sofia Alvarez',
    status: 'concluded',
    startedAt: '2026-04-18T09:00:00Z',
    endedAt: '2026-05-02T09:00:00Z',
  },
  {
    id: 'exp-cm-v1',
    modelId: 'content-mod',
    versionId: 'content-mod-v1',
    name: 'Text moderation launch',
    description: 'First automated review of text posts and comments.',
    goal: 'Automate the most common text-policy removals.',
    hypothesis:
      'A text classifier can flag the bulk of policy-violating posts.',
    owner: 'Sofia Alvarez',
    status: 'concluded',
    startedAt: '2026-01-08T09:00:00Z',
    endedAt: '2026-01-24T09:00:00Z',
  },
  {
    id: 'exp-ac-v2',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v2',
    name: 'Noisy audio robustness',
    description:
      'Train on background noise and overlapping speech to improve captions.',
    goal: 'Reduce word error rate on real-world noisy recordings.',
    hypothesis:
      'Noise-augmented training cuts word error rate by at least 3 points.',
    owner: 'Liam Nguyen',
    status: 'concluded',
    startedAt: '2026-04-25T09:00:00Z',
    endedAt: '2026-05-10T09:00:00Z',
  },
  {
    id: 'exp-ac-v1',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v1',
    name: 'Caption model launch',
    description: 'First speech-to-text captioning on clean studio audio.',
    goal: 'Ship usable live captions for recorded sessions.',
    hypothesis:
      'A speech-to-text model reaches under 10% word error rate on clean audio.',
    owner: 'Liam Nguyen',
    status: 'concluded',
    startedAt: '2026-02-12T09:00:00Z',
    endedAt: '2026-02-28T09:00:00Z',
  },
  {
    id: 'exp-ps-v2',
    modelId: 'photo-search',
    versionId: 'photo-search-v2',
    name: 'Text-to-image search',
    description:
      'Let people search photos by typing a description, not just by example.',
    goal: 'Match typed queries to the right photos at low latency.',
    hypothesis: 'A shared text-image embedding reaches recall@5 above 0.80.',
    owner: 'Hannah Kim',
    status: 'concluded',
    startedAt: '2026-04-20T09:00:00Z',
    endedAt: '2026-05-05T09:00:00Z',
  },
  {
    id: 'exp-ps-v1',
    modelId: 'photo-search',
    versionId: 'photo-search-v1',
    name: 'Similar-photo search launch',
    description: 'Find visually similar photos from an example image.',
    goal: 'Return visually similar photos quickly.',
    hypothesis:
      'Image embeddings retrieve visually similar photos with good recall.',
    owner: 'Hannah Kim',
    status: 'concluded',
    startedAt: '2026-02-24T09:00:00Z',
    endedAt: '2026-03-10T09:00:00Z',
  },
]

export const mockRuns: Run[] = [
  {
    id: 'r-vr-v1-a',
    experimentId: 'exp-vr-v1',
    name: 'popularity-baseline',
    status: 'completed',
    startedAt: '2026-01-11T10:00:00Z',
    endedAt: '2026-01-11T11:20:00Z',
    duration: '1h 20m',
    trigger: 'manual',
    environment: 'gpu-a100-x1',
    notes: 'Most-popular ordering, no personalization.',
    parameters: { lr: 0.01, batch_size: 128, epochs: 20, embed_dim: 48 },
    metrics: {
      click_through_rate: 4.8,
      watch_time_min: 3.6,
      'recall@10': 0.66,
    },
    series: {
      loss: series(0.9, -0.024, 0.02),
      click_through_rate: series(3.6, 0.06, 0.05),
    },
    datasetId: 'ds-video-v1',
    modelArch: 'Popularity ranker, 48-dim item embeddings.',
    artifactIds: [],
  },
  {
    id: 'r-vr-v1-b',
    experimentId: 'exp-vr-v1',
    name: 'personalized-feed',
    status: 'completed',
    startedAt: '2026-01-18T10:00:00Z',
    endedAt: '2026-01-18T13:10:00Z',
    duration: '3h 10m',
    trigger: 'ci',
    environment: 'gpu-a100-x2',
    notes: 'First personalized feed on watch history. Winning run.',
    parameters: { lr: 0.002, batch_size: 64, epochs: 40, embed_dim: 96 },
    metrics: {
      click_through_rate: 5.9,
      watch_time_min: 4.2,
      'recall@10': 0.74,
    },
    series: {
      loss: series(0.8, -0.02, 0.015),
      click_through_rate: series(4.2, 0.09, 0.04),
    },
    datasetId: 'ds-video-v1',
    modelArch: 'Two-tower ranker, 96-dim, watch-history features.',
    artifactIds: ['a-vr-v1-1'],
  },
  {
    id: 'r-vr-v2-a',
    experimentId: 'exp-vr-v2',
    name: 'feed-baseline',
    status: 'completed',
    startedAt: '2026-04-02T10:00:00Z',
    endedAt: '2026-04-02T13:30:00Z',
    duration: '3h 30m',
    trigger: 'manual',
    environment: 'gpu-a100-x2',
    notes: 'v1 feed re-trained on fresh data.',
    parameters: { lr: 0.002, batch_size: 64, epochs: 40, embed_dim: 96 },
    metrics: {
      click_through_rate: 6.0,
      watch_time_min: 4.3,
      'recall@10': 0.75,
    },
    series: {
      loss: series(0.78, -0.021, 0.015),
      click_through_rate: series(4.3, 0.09, 0.04),
    },
    datasetId: 'ds-video-v2',
    modelArch: 'Two-tower ranker, 96-dim, watch-history features.',
    artifactIds: [],
  },
  {
    id: 'r-vr-v2-b',
    experimentId: 'exp-vr-v2',
    name: 'watch-history-context',
    status: 'completed',
    startedAt: '2026-04-10T09:00:00Z',
    endedAt: '2026-04-10T13:12:00Z',
    duration: '4h 12m',
    trigger: 'ci',
    environment: 'gpu-a100-x4',
    notes: 'Adds session and watch-history context. Winning run.',
    parameters: { lr: 0.001, batch_size: 32, epochs: 50, embed_dim: 128 },
    metrics: {
      click_through_rate: 6.7,
      watch_time_min: 4.7,
      'recall@10': 0.81,
    },
    series: {
      loss: series(0.72, -0.021, 0.012),
      click_through_rate: series(4.7, 0.1, 0.03),
    },
    datasetId: 'ds-video-v2',
    modelArch: 'Two-tower ranker, 128-dim + session context features.',
    artifactIds: ['a-vr-v2-1', 'a-vr-v2-2'],
  },
  {
    id: 'r-pr-v1-a',
    experimentId: 'exp-pr-v1',
    name: 'bestseller-baseline',
    status: 'completed',
    startedAt: '2026-01-16T10:00:00Z',
    endedAt: '2026-01-16T11:05:00Z',
    duration: '1h 05m',
    trigger: 'manual',
    environment: 'gpu-a100-x1',
    notes: 'Best-seller ordering, no personalization.',
    parameters: { lr: 0.01, batch_size: 128, epochs: 20, embed_dim: 48 },
    metrics: {
      add_to_cart_rate: 3.1,
      'recall@10': 0.62,
      revenue_per_visit: 1.84,
    },
    series: {
      loss: series(0.92, -0.024, 0.02),
      add_to_cart_rate: series(2.2, 0.05, 0.04),
    },
    datasetId: 'ds-product-v1',
    modelArch: 'Best-seller ranker, 48-dim item embeddings.',
    artifactIds: [],
  },
  {
    id: 'r-pr-v1-b',
    experimentId: 'exp-pr-v1',
    name: 'purchase-history-ranker',
    status: 'completed',
    startedAt: '2026-01-23T10:00:00Z',
    endedAt: '2026-01-23T13:20:00Z',
    duration: '3h 20m',
    trigger: 'ci',
    environment: 'gpu-a100-x2',
    notes: 'Personalized on purchase history. Winning run.',
    parameters: { lr: 0.002, batch_size: 64, epochs: 40, embed_dim: 96 },
    metrics: {
      add_to_cart_rate: 3.9,
      'recall@10': 0.71,
      revenue_per_visit: 2.15,
    },
    series: {
      loss: series(0.82, -0.02, 0.015),
      add_to_cart_rate: series(2.9, 0.07, 0.03),
    },
    datasetId: 'ds-product-v1',
    modelArch: 'Two-tower ranker, 96-dim, purchase-history features.',
    artifactIds: ['a-pr-v1-1'],
  },
  {
    id: 'r-pr-v2-a',
    experimentId: 'exp-pr-v2',
    name: 'product-baseline',
    status: 'completed',
    startedAt: '2026-03-29T10:00:00Z',
    endedAt: '2026-03-29T13:25:00Z',
    duration: '3h 25m',
    trigger: 'manual',
    environment: 'gpu-a100-x2',
    notes: 'v1 ranker re-trained on fresh data.',
    parameters: { lr: 0.002, batch_size: 64, epochs: 40, embed_dim: 96 },
    metrics: {
      add_to_cart_rate: 4.0,
      'recall@10': 0.72,
      revenue_per_visit: 2.18,
    },
    series: {
      loss: series(0.8, -0.021, 0.015),
      add_to_cart_rate: series(3.0, 0.07, 0.03),
    },
    datasetId: 'ds-product-v2',
    modelArch: 'Two-tower ranker, 96-dim, purchase-history features.',
    artifactIds: [],
  },
  {
    id: 'r-pr-v2-b',
    experimentId: 'exp-pr-v2',
    name: 'cart-aware-ranker',
    status: 'completed',
    startedAt: '2026-04-06T09:00:00Z',
    endedAt: '2026-04-06T13:40:00Z',
    duration: '4h 40m',
    trigger: 'ci',
    environment: 'gpu-a100-x4',
    notes: 'Adds live cart contents as context. Winning run.',
    parameters: { lr: 0.001, batch_size: 32, epochs: 50, embed_dim: 128 },
    metrics: {
      add_to_cart_rate: 4.3,
      'recall@10': 0.78,
      revenue_per_visit: 2.29,
    },
    series: {
      loss: series(0.74, -0.021, 0.012),
      add_to_cart_rate: series(3.3, 0.08, 0.03),
    },
    datasetId: 'ds-product-v2',
    modelArch: 'Two-tower ranker, 128-dim + cart-context features.',
    artifactIds: ['a-pr-v2-1', 'a-pr-v2-2'],
  },
  {
    id: 'r-ca-v1-a',
    experimentId: 'exp-ca-v1',
    name: 'prompt-baseline',
    status: 'completed',
    startedAt: '2026-02-02T10:00:00Z',
    endedAt: '2026-02-02T12:00:00Z',
    duration: '2h 00m',
    trigger: 'manual',
    environment: 'gpu-h100-x2',
    notes: 'Prompted assistant, no fine-tuning.',
    parameters: { temperature: 0.7, max_tokens: 512, top_p: 0.9 },
    metrics: { helpfulness: 3.4, resolution_rate: 48, response_time_s: 2.6 },
    series: { helpfulness: series(3.0, 0.02, 0.03) },
    datasetId: 'ds-chat-v1',
    modelArch: 'Prompted base LLM, fixed instructions.',
    artifactIds: [],
  },
  {
    id: 'r-ca-v1-b',
    experimentId: 'exp-ca-v1',
    name: 'tuned-assistant',
    status: 'completed',
    startedAt: '2026-02-09T09:00:00Z',
    endedAt: '2026-02-09T17:30:00Z',
    duration: '8h 30m',
    trigger: 'ci',
    environment: 'gpu-h100-x4',
    notes: 'Fine-tuned on past support chats. Winning run.',
    parameters: { lr: 0.00002, batch_size: 8, epochs: 3, max_tokens: 512 },
    metrics: { helpfulness: 3.9, resolution_rate: 56, response_time_s: 2.2 },
    series: {
      loss: series(1.1, -0.03, 0.02),
      helpfulness: series(3.2, 0.035, 0.02),
    },
    datasetId: 'ds-chat-v1',
    modelArch: 'Fine-tuned LLM on support transcripts.',
    artifactIds: ['a-ca-v1-1'],
  },
  {
    id: 'r-ca-v2-a',
    experimentId: 'exp-ca-v2',
    name: 'tuned-no-retrieval',
    status: 'completed',
    startedAt: '2026-04-26T09:00:00Z',
    endedAt: '2026-04-26T17:00:00Z',
    duration: '8h 00m',
    trigger: 'manual',
    environment: 'gpu-h100-x4',
    notes: 'Fine-tuned assistant without document retrieval.',
    parameters: { lr: 0.00002, batch_size: 8, epochs: 3, max_tokens: 512 },
    metrics: { helpfulness: 4.0, resolution_rate: 58, response_time_s: 2.1 },
    series: {
      loss: series(1.0, -0.028, 0.02),
      helpfulness: series(3.3, 0.035, 0.02),
    },
    datasetId: 'ds-chat-v2',
    modelArch: 'Fine-tuned LLM, no retrieval.',
    artifactIds: [],
  },
  {
    id: 'r-ca-v2-b',
    experimentId: 'exp-ca-v2',
    name: 'retrieval-grounded',
    status: 'completed',
    startedAt: '2026-05-03T09:00:00Z',
    endedAt: '2026-05-03T18:20:00Z',
    duration: '9h 20m',
    trigger: 'ci',
    environment: 'gpu-h100-x8',
    notes: 'Grounds answers in retrieved help-center articles. Winning run.',
    parameters: {
      lr: 0.00002,
      batch_size: 8,
      epochs: 3,
      max_tokens: 512,
      top_k_docs: 4,
    },
    metrics: { helpfulness: 4.4, resolution_rate: 68, response_time_s: 2.4 },
    series: {
      loss: series(0.95, -0.028, 0.02),
      helpfulness: series(3.6, 0.04, 0.02),
    },
    datasetId: 'ds-chat-v2',
    modelArch: 'Retrieval-augmented fine-tuned LLM.',
    artifactIds: ['a-ca-v2-1', 'a-ca-v2-2'],
  },
  {
    id: 'r-sf-v1-a',
    experimentId: 'exp-sf-v1',
    name: 'rules-baseline',
    status: 'completed',
    startedAt: '2025-12-06T10:00:00Z',
    endedAt: '2025-12-06T10:20:00Z',
    duration: '0h 20m',
    trigger: 'manual',
    environment: 'cpu-16c',
    notes: 'Hand-written spam rules reference.',
    parameters: { rule_count: 180, threshold: 0.5 },
    metrics: { accuracy: 92.1, precision: 0.9, false_positive_rate: 1.8 },
    series: { accuracy: series(92.1, 0, 0.05) },
    datasetId: 'ds-spam-v1',
    modelArch: 'Hand-written rule engine.',
    artifactIds: [],
  },
  {
    id: 'r-sf-v1-b',
    experimentId: 'exp-sf-v1',
    name: 'text-classifier',
    status: 'completed',
    startedAt: '2025-12-13T10:00:00Z',
    endedAt: '2025-12-13T11:10:00Z',
    duration: '1h 10m',
    trigger: 'ci',
    environment: 'gpu-a100-x1',
    notes: 'Learned classifier on email text. Winning run.',
    parameters: { lr: 0.001, batch_size: 64, epochs: 15 },
    metrics: { accuracy: 96.4, precision: 0.95, false_positive_rate: 0.6 },
    series: {
      loss: series(0.7, -0.02, 0.01),
      accuracy: series(90, 0.32, 0.1),
    },
    datasetId: 'ds-spam-v1',
    modelArch: 'Text classifier on subject and body.',
    artifactIds: ['a-sf-v1-1'],
  },
  {
    id: 'r-sf-v2-a',
    experimentId: 'exp-sf-v2',
    name: 'text-only-refresh',
    status: 'completed',
    startedAt: '2026-03-21T10:00:00Z',
    endedAt: '2026-03-21T11:15:00Z',
    duration: '1h 15m',
    trigger: 'manual',
    environment: 'gpu-a100-x1',
    notes: 'v1 classifier re-trained on fresh mail.',
    parameters: { lr: 0.001, batch_size: 64, epochs: 15 },
    metrics: { accuracy: 96.6, precision: 0.95, false_positive_rate: 0.6 },
    series: {
      loss: series(0.68, -0.02, 0.01),
      accuracy: series(90, 0.34, 0.1),
    },
    datasetId: 'ds-spam-v2',
    modelArch: 'Text classifier on subject and body.',
    artifactIds: [],
  },
  {
    id: 'r-sf-v2-b',
    experimentId: 'exp-sf-v2',
    name: 'phishing-features',
    status: 'completed',
    startedAt: '2026-03-28T09:00:00Z',
    endedAt: '2026-03-28T10:35:00Z',
    duration: '1h 35m',
    trigger: 'ci',
    environment: 'gpu-a100-x2',
    notes: 'Adds link and sender-reputation features. Winning run.',
    parameters: { lr: 0.001, batch_size: 64, epochs: 20 },
    metrics: { accuracy: 98.2, precision: 0.97, false_positive_rate: 0.3 },
    series: {
      loss: series(0.6, -0.02, 0.01),
      accuracy: series(92, 0.3, 0.08),
    },
    datasetId: 'ds-spam-v2',
    modelArch: 'Text + link + sender-reputation features.',
    artifactIds: ['a-sf-v2-1', 'a-sf-v2-2'],
  },
  {
    id: 'r-cm-v1-a',
    experimentId: 'exp-cm-v1',
    name: 'keyword-baseline',
    status: 'completed',
    startedAt: '2026-01-09T10:00:00Z',
    endedAt: '2026-01-09T10:25:00Z',
    duration: '0h 25m',
    trigger: 'manual',
    environment: 'cpu-16c',
    notes: 'Keyword blocklist reference.',
    parameters: { blocklist_size: 4200, threshold: 0.5 },
    metrics: { precision: 0.78, recall: 0.61, false_positive_rate: 3.4 },
    series: { recall: series(0.61, 0, 0.004) },
    datasetId: 'ds-content-v1',
    modelArch: 'Keyword blocklist matcher.',
    artifactIds: [],
  },
  {
    id: 'r-cm-v1-b',
    experimentId: 'exp-cm-v1',
    name: 'text-moderator',
    status: 'completed',
    startedAt: '2026-01-16T09:00:00Z',
    endedAt: '2026-01-16T13:00:00Z',
    duration: '4h 00m',
    trigger: 'ci',
    environment: 'gpu-a100-x2',
    notes: 'Learned text moderation classifier. Winning run.',
    parameters: { lr: 0.0005, batch_size: 32, epochs: 10 },
    metrics: { precision: 0.86, recall: 0.79, false_positive_rate: 1.6 },
    series: {
      loss: series(0.9, -0.026, 0.02),
      recall: series(0.5, 0.016, 0.01),
    },
    datasetId: 'ds-content-v1',
    modelArch: 'Transformer text classifier.',
    artifactIds: ['a-cm-v1-1'],
  },
  {
    id: 'r-cm-v2-a',
    experimentId: 'exp-cm-v2',
    name: 'text-only-refresh',
    status: 'completed',
    startedAt: '2026-04-19T10:00:00Z',
    endedAt: '2026-04-19T14:10:00Z',
    duration: '4h 10m',
    trigger: 'manual',
    environment: 'gpu-a100-x2',
    notes: 'v1 text moderator re-trained on fresh reports.',
    parameters: { lr: 0.0005, batch_size: 32, epochs: 10 },
    metrics: { precision: 0.87, recall: 0.8, false_positive_rate: 1.5 },
    series: {
      loss: series(0.85, -0.026, 0.02),
      recall: series(0.52, 0.016, 0.01),
    },
    datasetId: 'ds-content-v2',
    modelArch: 'Transformer text classifier.',
    artifactIds: [],
  },
  {
    id: 'r-cm-v2-b',
    experimentId: 'exp-cm-v2',
    name: 'image-text-moderator',
    status: 'completed',
    startedAt: '2026-04-26T09:00:00Z',
    endedAt: '2026-04-26T16:30:00Z',
    duration: '7h 30m',
    trigger: 'ci',
    environment: 'gpu-h100-x4',
    notes: 'Reviews attached images with text. Winning run.',
    parameters: { lr: 0.0003, batch_size: 16, epochs: 12 },
    metrics: { precision: 0.9, recall: 0.91, false_positive_rate: 1.1 },
    series: {
      loss: series(0.95, -0.028, 0.02),
      recall: series(0.55, 0.018, 0.01),
    },
    datasetId: 'ds-content-v2',
    modelArch: 'Multimodal image + text classifier.',
    artifactIds: ['a-cm-v2-1', 'a-cm-v2-2'],
  },
  {
    id: 'r-ac-v1-a',
    experimentId: 'exp-ac-v1',
    name: 'small-model-baseline',
    status: 'completed',
    startedAt: '2026-02-13T10:00:00Z',
    endedAt: '2026-02-13T18:00:00Z',
    duration: '8h 00m',
    trigger: 'manual',
    environment: 'gpu-a100-x2',
    notes: 'Small speech-to-text model on clean audio.',
    parameters: { lr: 0.0004, batch_size: 24, epochs: 20 },
    metrics: { word_error_rate: 11.8, accuracy: 88.2, latency_ms: 180 },
    series: { word_error_rate: series(24, -0.62, 0.3) },
    datasetId: 'ds-captions-v1',
    modelArch: 'Small encoder-decoder speech model.',
    artifactIds: [],
  },
  {
    id: 'r-ac-v1-b',
    experimentId: 'exp-ac-v1',
    name: 'base-model',
    status: 'completed',
    startedAt: '2026-02-20T09:00:00Z',
    endedAt: '2026-02-21T03:00:00Z',
    duration: '18h 00m',
    trigger: 'ci',
    environment: 'gpu-h100-x4',
    notes: 'Larger model on clean studio audio. Winning run.',
    parameters: { lr: 0.0003, batch_size: 16, epochs: 25 },
    metrics: { word_error_rate: 9.4, accuracy: 90.6, latency_ms: 240 },
    series: {
      loss: series(1.2, -0.03, 0.02),
      word_error_rate: series(22, -0.62, 0.25),
    },
    datasetId: 'ds-captions-v1',
    modelArch: 'Encoder-decoder speech model, base size.',
    artifactIds: ['a-ac-v1-1'],
  },
  {
    id: 'r-ac-v2-a',
    experimentId: 'exp-ac-v2',
    name: 'clean-only-refresh',
    status: 'completed',
    startedAt: '2026-04-26T09:00:00Z',
    endedAt: '2026-04-27T03:00:00Z',
    duration: '18h 00m',
    trigger: 'manual',
    environment: 'gpu-h100-x4',
    notes: 'v1 model re-trained on clean audio only.',
    parameters: { lr: 0.0003, batch_size: 16, epochs: 25 },
    metrics: { word_error_rate: 9.2, accuracy: 90.8, latency_ms: 235 },
    series: {
      loss: series(1.15, -0.03, 0.02),
      word_error_rate: series(21, -0.6, 0.25),
    },
    datasetId: 'ds-captions-v2',
    modelArch: 'Encoder-decoder speech model, base size.',
    artifactIds: [],
  },
  {
    id: 'r-ac-v2-b',
    experimentId: 'exp-ac-v2',
    name: 'noise-augmented',
    status: 'completed',
    startedAt: '2026-05-03T09:00:00Z',
    endedAt: '2026-05-04T05:00:00Z',
    duration: '20h 00m',
    trigger: 'ci',
    environment: 'gpu-h100-x8',
    notes: 'Trained with background noise and overlapping speech. Winning run.',
    parameters: { lr: 0.0003, batch_size: 16, epochs: 30, noise_aug: 0.4 },
    metrics: { word_error_rate: 6.1, accuracy: 93.9, latency_ms: 250 },
    series: {
      loss: series(1.05, -0.03, 0.02),
      word_error_rate: series(18, -0.6, 0.2),
    },
    datasetId: 'ds-captions-v2',
    modelArch: 'Noise-augmented encoder-decoder speech model.',
    artifactIds: ['a-ac-v2-1', 'a-ac-v2-2'],
  },
  {
    id: 'r-ps-v1-a',
    experimentId: 'exp-ps-v1',
    name: 'color-histogram-baseline',
    status: 'completed',
    startedAt: '2026-02-25T10:00:00Z',
    endedAt: '2026-02-25T11:00:00Z',
    duration: '1h 00m',
    trigger: 'manual',
    environment: 'gpu-a100-x1',
    notes: 'Classic color-histogram similarity.',
    parameters: { bins: 256, metric: 'cosine' },
    metrics: { 'recall@5': 0.58, 'precision@5': 0.52, latency_ms: 18 },
    series: { 'recall@5': series(0.58, 0, 0.004) },
    datasetId: 'ds-photo-v1',
    modelArch: 'Color-histogram feature matcher.',
    artifactIds: [],
  },
  {
    id: 'r-ps-v1-b',
    experimentId: 'exp-ps-v1',
    name: 'image-embeddings',
    status: 'completed',
    startedAt: '2026-03-04T09:00:00Z',
    endedAt: '2026-03-04T15:00:00Z',
    duration: '6h 00m',
    trigger: 'ci',
    environment: 'gpu-a100-x4',
    notes: 'Learned image embeddings for similarity. Winning run.',
    parameters: { lr: 0.0005, batch_size: 128, epochs: 30, embed_dim: 512 },
    metrics: { 'recall@5': 0.73, 'precision@5': 0.66, latency_ms: 20 },
    series: {
      loss: series(0.85, -0.024, 0.015),
      'recall@5': series(0.45, 0.016, 0.008),
    },
    datasetId: 'ds-photo-v1',
    modelArch: 'Image encoder, 512-dim embeddings.',
    artifactIds: ['a-ps-v1-1'],
  },
  {
    id: 'r-ps-v2-a',
    experimentId: 'exp-ps-v2',
    name: 'image-only-refresh',
    status: 'completed',
    startedAt: '2026-04-21T09:00:00Z',
    endedAt: '2026-04-21T15:10:00Z',
    duration: '6h 10m',
    trigger: 'manual',
    environment: 'gpu-a100-x4',
    notes: 'v1 image embeddings re-trained on fresh photos.',
    parameters: { lr: 0.0005, batch_size: 128, epochs: 30, embed_dim: 512 },
    metrics: { 'recall@5': 0.74, 'precision@5': 0.67, latency_ms: 20 },
    series: {
      loss: series(0.82, -0.024, 0.015),
      'recall@5': series(0.46, 0.016, 0.008),
    },
    datasetId: 'ds-photo-v2',
    modelArch: 'Image encoder, 512-dim embeddings.',
    artifactIds: [],
  },
  {
    id: 'r-ps-v2-b',
    experimentId: 'exp-ps-v2',
    name: 'text-image-embeddings',
    status: 'completed',
    startedAt: '2026-04-28T09:00:00Z',
    endedAt: '2026-04-28T17:30:00Z',
    duration: '8h 30m',
    trigger: 'ci',
    environment: 'gpu-h100-x4',
    notes: 'Shared text-image embedding for typed queries. Winning run.',
    parameters: { lr: 0.0004, batch_size: 96, epochs: 35, embed_dim: 512 },
    metrics: { 'recall@5': 0.82, 'precision@5': 0.74, latency_ms: 22 },
    series: {
      loss: series(0.78, -0.024, 0.012),
      'recall@5': series(0.5, 0.018, 0.008),
    },
    datasetId: 'ds-photo-v2',
    modelArch: 'Shared text-image encoder, 512-dim embeddings.',
    artifactIds: ['a-ps-v2-1', 'a-ps-v2-2'],
  },
]

export const mockArtifacts: Artifact[] = [
  {
    id: 'a-vr-v1-1',
    runId: 'r-vr-v1-b',
    name: 'checkpoint.pt',
    type: 'Model checkpoint',
    description: 'Personalized feed weights.',
    uri: 's3://uigraph/video-recs/r-vr-v1-b/checkpoint.pt',
    size: '142 MB',
    format: 'PyTorch',
    createdAt: '2026-01-18T13:10:00Z',
  },
  {
    id: 'a-vr-v2-1',
    runId: 'r-vr-v2-b',
    name: 'model.onnx',
    type: 'ONNX',
    description: 'Exported ranking model for serving.',
    uri: 's3://uigraph/video-recs/r-vr-v2-b/model.onnx',
    size: '168 MB',
    format: 'ONNX',
    createdAt: '2026-04-10T13:12:00Z',
  },
  {
    id: 'a-vr-v2-2',
    runId: 'r-vr-v2-b',
    name: 'watch-time-analysis.ipynb',
    type: 'Notebook',
    description: 'Watch-time lift analysis by audience segment.',
    uri: 's3://uigraph/video-recs/r-vr-v2-b/watch-time-analysis.ipynb',
    size: '1.4 MB',
    format: 'Jupyter',
    createdAt: '2026-04-10T15:00:00Z',
  },
  {
    id: 'a-pr-v1-1',
    runId: 'r-pr-v1-b',
    name: 'checkpoint.pt',
    type: 'Model checkpoint',
    description: 'Purchase-history ranker weights.',
    uri: 's3://uigraph/product-recs/r-pr-v1-b/checkpoint.pt',
    size: '138 MB',
    format: 'PyTorch',
    createdAt: '2026-01-23T13:20:00Z',
  },
  {
    id: 'a-pr-v2-1',
    runId: 'r-pr-v2-b',
    name: 'model.onnx',
    type: 'ONNX',
    description: 'Cart-aware ranker export for serving.',
    uri: 's3://uigraph/product-recs/r-pr-v2-b/model.onnx',
    size: '172 MB',
    format: 'ONNX',
    createdAt: '2026-04-06T13:40:00Z',
  },
  {
    id: 'a-pr-v2-2',
    runId: 'r-pr-v2-b',
    name: 'revenue-lift.png',
    type: 'Plot',
    description: 'Revenue per visit by cart size.',
    uri: 's3://uigraph/product-recs/r-pr-v2-b/revenue-lift.png',
    size: '188 KB',
    format: 'PNG',
    createdAt: '2026-04-06T14:00:00Z',
  },
  {
    id: 'a-ca-v1-1',
    runId: 'r-ca-v1-b',
    name: 'adapter.safetensors',
    type: 'Model checkpoint',
    description: 'Fine-tuning adapter weights.',
    uri: 's3://uigraph/chat-assistant/r-ca-v1-b/adapter.safetensors',
    size: '320 MB',
    format: 'Safetensors',
    createdAt: '2026-02-09T17:30:00Z',
  },
  {
    id: 'a-ca-v2-1',
    runId: 'r-ca-v2-b',
    name: 'adapter.safetensors',
    type: 'Model checkpoint',
    description: 'Retrieval-grounded adapter weights.',
    uri: 's3://uigraph/chat-assistant/r-ca-v2-b/adapter.safetensors',
    size: '336 MB',
    format: 'Safetensors',
    createdAt: '2026-05-03T18:20:00Z',
  },
  {
    id: 'a-ca-v2-2',
    runId: 'r-ca-v2-b',
    name: 'answer-review.ipynb',
    type: 'Notebook',
    description: 'Human review of grounded vs ungrounded answers.',
    uri: 's3://uigraph/chat-assistant/r-ca-v2-b/answer-review.ipynb',
    size: '2.3 MB',
    format: 'Jupyter',
    createdAt: '2026-05-03T19:00:00Z',
  },
  {
    id: 'a-sf-v1-1',
    runId: 'r-sf-v1-b',
    name: 'model.pkl',
    type: 'Model checkpoint',
    description: 'Serialized spam text classifier.',
    uri: 's3://uigraph/spam-filter/r-sf-v1-b/model.pkl',
    size: '24 MB',
    format: 'Pickle',
    createdAt: '2025-12-13T11:10:00Z',
  },
  {
    id: 'a-sf-v2-1',
    runId: 'r-sf-v2-b',
    name: 'model.pkl',
    type: 'Model checkpoint',
    description: 'Spam classifier with phishing features.',
    uri: 's3://uigraph/spam-filter/r-sf-v2-b/model.pkl',
    size: '31 MB',
    format: 'Pickle',
    createdAt: '2026-03-28T10:35:00Z',
  },
  {
    id: 'a-sf-v2-2',
    runId: 'r-sf-v2-b',
    name: 'confusion.png',
    type: 'Confusion matrix',
    description: 'Confusion matrix on held-out mail.',
    uri: 's3://uigraph/spam-filter/r-sf-v2-b/confusion.png',
    size: '82 KB',
    format: 'PNG',
    createdAt: '2026-03-28T10:36:00Z',
  },
  {
    id: 'a-cm-v1-1',
    runId: 'r-cm-v1-b',
    name: 'checkpoint.pt',
    type: 'Model checkpoint',
    description: 'Text moderation classifier weights.',
    uri: 's3://uigraph/content-mod/r-cm-v1-b/checkpoint.pt',
    size: '210 MB',
    format: 'PyTorch',
    createdAt: '2026-01-16T13:00:00Z',
  },
  {
    id: 'a-cm-v2-1',
    runId: 'r-cm-v2-b',
    name: 'checkpoint.pt',
    type: 'Model checkpoint',
    description: 'Multimodal moderation model weights.',
    uri: 's3://uigraph/content-mod/r-cm-v2-b/checkpoint.pt',
    size: '486 MB',
    format: 'PyTorch',
    createdAt: '2026-04-26T16:30:00Z',
  },
  {
    id: 'a-cm-v2-2',
    runId: 'r-cm-v2-b',
    name: 'confusion.png',
    type: 'Confusion matrix',
    description: 'Confusion matrix across policy categories.',
    uri: 's3://uigraph/content-mod/r-cm-v2-b/confusion.png',
    size: '120 KB',
    format: 'PNG',
    createdAt: '2026-04-26T16:31:00Z',
  },
  {
    id: 'a-ac-v1-1',
    runId: 'r-ac-v1-b',
    name: 'model.gguf',
    type: 'GGUF',
    description: 'Quantized caption model for on-device use.',
    uri: 's3://uigraph/auto-captions/r-ac-v1-b/model.gguf',
    size: '540 MB',
    format: 'GGUF',
    createdAt: '2026-02-21T03:05:00Z',
  },
  {
    id: 'a-ac-v2-1',
    runId: 'r-ac-v2-b',
    name: 'model.gguf',
    type: 'GGUF',
    description: 'Noise-robust caption model, quantized.',
    uri: 's3://uigraph/auto-captions/r-ac-v2-b/model.gguf',
    size: '565 MB',
    format: 'GGUF',
    createdAt: '2026-05-04T05:05:00Z',
  },
  {
    id: 'a-ac-v2-2',
    runId: 'r-ac-v2-b',
    name: 'wer-by-noise.png',
    type: 'Plot',
    description: 'Word error rate across noise levels.',
    uri: 's3://uigraph/auto-captions/r-ac-v2-b/wer-by-noise.png',
    size: '96 KB',
    format: 'PNG',
    createdAt: '2026-05-04T05:10:00Z',
  },
  {
    id: 'a-ps-v1-1',
    runId: 'r-ps-v1-b',
    name: 'image-encoder.onnx',
    type: 'ONNX',
    description: 'Image embedding encoder for indexing.',
    uri: 's3://uigraph/photo-search/r-ps-v1-b/image-encoder.onnx',
    size: '248 MB',
    format: 'ONNX',
    createdAt: '2026-03-04T15:00:00Z',
  },
  {
    id: 'a-ps-v2-1',
    runId: 'r-ps-v2-b',
    name: 'text-image-encoder.onnx',
    type: 'ONNX',
    description: 'Shared text-image encoder for typed search.',
    uri: 's3://uigraph/photo-search/r-ps-v2-b/text-image-encoder.onnx',
    size: '412 MB',
    format: 'ONNX',
    createdAt: '2026-04-28T17:30:00Z',
  },
  {
    id: 'a-ps-v2-2',
    runId: 'r-ps-v2-b',
    name: 'retrieval-examples.ipynb',
    type: 'Notebook',
    description: 'Example typed queries and top results.',
    uri: 's3://uigraph/photo-search/r-ps-v2-b/retrieval-examples.ipynb',
    size: '3.1 MB',
    format: 'Jupyter',
    createdAt: '2026-04-28T18:00:00Z',
  },
]

export const mockDatasets: Dataset[] = [
  {
    id: 'ds-video-v2',
    modelId: 'video-recs',
    versionId: 'video-recs-v2',
    name: 'video-watch-events',
    version: 'v2.0.0',
    description:
      'Watch events enriched with session and watch-history context.',
    source: 's3://data-lake/video/watch-events/v2',
    type: 'tabular',
    size: '26 GB',
    rowCount: 62_000_000,
    schema: [
      { name: 'user_id', type: 'string', description: 'Hashed viewer id.' },
      { name: 'video_id', type: 'string', description: 'Video identifier.' },
      {
        name: 'watch_seconds',
        type: 'int',
        description: 'Seconds watched in the session.',
      },
      { name: 'clicked', type: 'bool', description: 'Was the video clicked.' },
      {
        name: 'session_context',
        type: 'float[16]',
        description: '16 session context features.',
      },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    parentId: 'ds-video-v1',
    tags: ['augmented', 'pii'],
    createdAt: '2026-03-30T09:00:00Z',
  },
  {
    id: 'ds-video-v1',
    modelId: 'video-recs',
    versionId: 'video-recs-v1',
    name: 'video-watch-events',
    version: 'v1.0.0',
    description: 'Baseline watch events without session context.',
    source: 's3://data-lake/video/watch-events/v1',
    type: 'tabular',
    size: '18 GB',
    rowCount: 45_000_000,
    schema: [
      { name: 'user_id', type: 'string', description: 'Hashed viewer id.' },
      { name: 'video_id', type: 'string', description: 'Video identifier.' },
      {
        name: 'watch_seconds',
        type: 'int',
        description: 'Seconds watched in the session.',
      },
      { name: 'clicked', type: 'bool', description: 'Was the video clicked.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    tags: ['pii'],
    createdAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'ds-product-v2',
    modelId: 'product-recs',
    versionId: 'product-recs-v2',
    name: 'shopping-events',
    version: 'v2.0.0',
    description: 'Shopping events enriched with live cart contents.',
    source: 's3://data-lake/shopping/events/v2',
    type: 'tabular',
    size: '20 GB',
    rowCount: 51_000_000,
    schema: [
      { name: 'user_id', type: 'string', description: 'Hashed shopper id.' },
      {
        name: 'product_id',
        type: 'string',
        description: 'Product identifier.',
      },
      {
        name: 'event_type',
        type: 'enum',
        description: 'view | add_to_cart | purchase.',
      },
      {
        name: 'cart_contents',
        type: 'string[]',
        description: 'Product ids currently in the cart.',
      },
      { name: 'price', type: 'float', description: 'Product price at event.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    parentId: 'ds-product-v1',
    tags: ['augmented', 'pii'],
    createdAt: '2026-03-26T09:00:00Z',
  },
  {
    id: 'ds-product-v1',
    modelId: 'product-recs',
    versionId: 'product-recs-v1',
    name: 'shopping-events',
    version: 'v1.0.0',
    description: 'Baseline shopping events without cart context.',
    source: 's3://data-lake/shopping/events/v1',
    type: 'tabular',
    size: '14 GB',
    rowCount: 38_000_000,
    schema: [
      { name: 'user_id', type: 'string', description: 'Hashed shopper id.' },
      {
        name: 'product_id',
        type: 'string',
        description: 'Product identifier.',
      },
      {
        name: 'event_type',
        type: 'enum',
        description: 'view | add_to_cart | purchase.',
      },
      { name: 'price', type: 'float', description: 'Product price at event.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    tags: ['pii'],
    createdAt: '2026-01-18T09:00:00Z',
  },
  {
    id: 'ds-chat-v2',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v2',
    name: 'support-conversations',
    version: 'v2.0.0',
    description:
      'Resolved support chats paired with the help-center articles used to answer.',
    source: 's3://data-lake/support/conversations/v2',
    type: 'text',
    size: '4.8 GB',
    rowCount: 820_000,
    schema: [
      { name: 'question', type: 'string', description: 'Customer question.' },
      { name: 'answer', type: 'string', description: 'Agent or model answer.' },
      {
        name: 'source_docs',
        type: 'string[]',
        description: 'Help-center article ids cited.',
      },
      {
        name: 'resolved',
        type: 'bool',
        description: 'Was the issue resolved.',
      },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    parentId: 'ds-chat-v1',
    tags: ['augmented', 'pii'],
    createdAt: '2026-04-28T09:00:00Z',
  },
  {
    id: 'ds-chat-v1',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v1',
    name: 'support-conversations',
    version: 'v1.0.0',
    description: 'Past support chats without linked source articles.',
    source: 's3://data-lake/support/conversations/v1',
    type: 'text',
    size: '2.6 GB',
    rowCount: 540_000,
    schema: [
      { name: 'question', type: 'string', description: 'Customer question.' },
      { name: 'answer', type: 'string', description: 'Agent answer.' },
      {
        name: 'resolved',
        type: 'bool',
        description: 'Was the issue resolved.',
      },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    tags: ['pii'],
    createdAt: '2026-02-04T09:00:00Z',
  },
  {
    id: 'ds-spam-v2',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v2',
    name: 'email-labels',
    version: 'v2.0.0',
    description: 'Labeled emails with link and sender-reputation features.',
    source: 's3://data-lake/email/labels/v2',
    type: 'text',
    size: '3.2 GB',
    rowCount: 9_400_000,
    schema: [
      { name: 'subject', type: 'string', description: 'Email subject line.' },
      { name: 'body', type: 'string', description: 'Email body text.' },
      {
        name: 'link_reputation',
        type: 'float',
        description: 'Reputation score of linked domains.',
      },
      {
        name: 'sender_score',
        type: 'float',
        description: 'Sender reputation score.',
      },
      { name: 'label', type: 'enum', description: 'ham | spam | phishing.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    parentId: 'ds-spam-v1',
    tags: ['augmented', 'pii'],
    createdAt: '2026-03-22T09:00:00Z',
  },
  {
    id: 'ds-spam-v1',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v1',
    name: 'email-labels',
    version: 'v1.0.0',
    description: 'Labeled emails using subject and body text only.',
    source: 's3://data-lake/email/labels/v1',
    type: 'text',
    size: '2.1 GB',
    rowCount: 7_100_000,
    schema: [
      { name: 'subject', type: 'string', description: 'Email subject line.' },
      { name: 'body', type: 'string', description: 'Email body text.' },
      { name: 'label', type: 'enum', description: 'ham | spam.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    tags: ['pii'],
    createdAt: '2025-12-08T09:00:00Z',
  },
  {
    id: 'ds-content-v2',
    modelId: 'content-mod',
    versionId: 'content-mod-v2',
    name: 'moderation-reports',
    version: 'v2.0.0',
    description: 'Reported posts with text and attached images, human-labeled.',
    source: 's3://data-lake/moderation/reports/v2',
    type: 'multimodal',
    size: '9.5 GB',
    rowCount: 3_400_000,
    schema: [
      {
        name: 'post_text',
        type: 'string',
        description: 'Post or comment text.',
      },
      {
        name: 'image_uri',
        type: 'string',
        description: 'Attached image reference.',
      },
      {
        name: 'category',
        type: 'enum',
        description: 'safe | harassment | violence | adult.',
      },
      { name: 'action', type: 'enum', description: 'allow | remove.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    parentId: 'ds-content-v1',
    tags: ['augmented', 'sensitive'],
    createdAt: '2026-04-20T09:00:00Z',
  },
  {
    id: 'ds-content-v1',
    modelId: 'content-mod',
    versionId: 'content-mod-v1',
    name: 'moderation-reports',
    version: 'v1.0.0',
    description: 'Reported text posts and comments, human-labeled.',
    source: 's3://data-lake/moderation/reports/v1',
    type: 'text',
    size: '2.8 GB',
    rowCount: 2_100_000,
    schema: [
      {
        name: 'post_text',
        type: 'string',
        description: 'Post or comment text.',
      },
      {
        name: 'category',
        type: 'enum',
        description: 'safe | harassment | violence | adult.',
      },
      { name: 'action', type: 'enum', description: 'allow | remove.' },
    ],
    split: { train: 80, validation: 10, test: 10 },
    license: 'Internal',
    tags: ['sensitive'],
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'ds-captions-v2',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v2',
    name: 'speech-recordings',
    version: 'v2.0.0',
    description:
      'Transcribed recordings with added background noise and overlap.',
    source: 's3://data-lake/speech/recordings/v2',
    type: 'audio',
    size: '340 GB',
    rowCount: 1_200_000,
    schema: [
      {
        name: 'audio_uri',
        type: 'string',
        description: 'Audio clip reference.',
      },
      {
        name: 'transcript',
        type: 'string',
        description: 'Reference transcript.',
      },
      {
        name: 'noise_level',
        type: 'float',
        description: 'Added background noise level.',
      },
      {
        name: 'speakers',
        type: 'int',
        description: 'Number of overlapping speakers.',
      },
    ],
    split: { train: 85, validation: 8, test: 7 },
    license: 'CC-BY-4.0',
    parentId: 'ds-captions-v1',
    tags: ['augmented', 'noise'],
    createdAt: '2026-04-24T09:00:00Z',
  },
  {
    id: 'ds-captions-v1',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v1',
    name: 'speech-recordings',
    version: 'v1.0.0',
    description: 'Transcribed clean studio recordings.',
    source: 's3://data-lake/speech/recordings/v1',
    type: 'audio',
    size: '180 GB',
    rowCount: 640_000,
    schema: [
      {
        name: 'audio_uri',
        type: 'string',
        description: 'Audio clip reference.',
      },
      {
        name: 'transcript',
        type: 'string',
        description: 'Reference transcript.',
      },
    ],
    split: { train: 85, validation: 8, test: 7 },
    license: 'CC-BY-4.0',
    tags: ['clean'],
    createdAt: '2026-02-14T09:00:00Z',
  },
  {
    id: 'ds-photo-v2',
    modelId: 'photo-search',
    versionId: 'photo-search-v2',
    name: 'photo-captions',
    version: 'v2.0.0',
    description: 'Photos paired with text captions for text-to-image search.',
    source: 's3://data-lake/photos/captions/v2',
    type: 'image',
    size: '210 GB',
    rowCount: 12_000_000,
    schema: [
      { name: 'photo_uri', type: 'string', description: 'Photo reference.' },
      {
        name: 'caption',
        type: 'string',
        description: 'Text caption of the photo.',
      },
      {
        name: 'tags',
        type: 'string[]',
        description: 'Object and scene tags.',
      },
    ],
    split: { train: 90, validation: 5, test: 5 },
    license: 'Internal',
    parentId: 'ds-photo-v1',
    tags: ['augmented', 'captions'],
    createdAt: '2026-04-22T09:00:00Z',
  },
  {
    id: 'ds-photo-v1',
    modelId: 'photo-search',
    versionId: 'photo-search-v1',
    name: 'photo-captions',
    version: 'v1.0.0',
    description: 'Photos with object tags for image-to-image similarity.',
    source: 's3://data-lake/photos/captions/v1',
    type: 'image',
    size: '120 GB',
    rowCount: 7_500_000,
    schema: [
      { name: 'photo_uri', type: 'string', description: 'Photo reference.' },
      {
        name: 'tags',
        type: 'string[]',
        description: 'Object and scene tags.',
      },
    ],
    split: { train: 90, validation: 5, test: 5 },
    license: 'Internal',
    tags: ['tags'],
    createdAt: '2026-02-26T09:00:00Z',
  },
]

export const mockEvaluations: Evaluation[] = [
  {
    id: 'ev-vr-v2',
    modelId: 'video-recs',
    versionId: 'video-recs-v2',
    name: 'Home-feed A/B test',
    type: 'Online A/B Test',
    description: '2-week online experiment at 20% of home-feed traffic.',
    summary: 'Click-through rate up 9% and average watch time up 12%.',
    evaluatedAt: '2026-04-28T09:00:00Z',
    evaluator: 'Growth Analytics',
    metrics: [
      {
        id: 'm-vr-v2-1',
        name: 'Click-through rate',
        value: 6.7,
        unit: '%',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-04-28T09:00:00Z',
      },
      {
        id: 'm-vr-v2-2',
        name: 'Watch time',
        value: 4.7,
        unit: 'min',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-04-28T09:00:00Z',
      },
      {
        id: 'm-vr-v2-3',
        name: 'Recall@10',
        value: 0.81,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-04-28T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-vr-v1',
    modelId: 'video-recs',
    versionId: 'video-recs-v1',
    name: 'Personalization offline benchmark',
    type: 'Offline Benchmark',
    description: 'Held-out comparison against the most-popular ordering.',
    summary: 'Personalized feed beats popularity on click-through rate.',
    evaluatedAt: '2026-01-25T09:00:00Z',
    evaluator: 'Maya Patel',
    metrics: [
      {
        id: 'm-vr-v1-1',
        name: 'Click-through rate',
        value: 5.9,
        unit: '%',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-01-25T09:00:00Z',
      },
      {
        id: 'm-vr-v1-2',
        name: 'Recall@10',
        value: 0.74,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-01-25T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-pr-v2',
    modelId: 'product-recs',
    versionId: 'product-recs-v2',
    name: 'Cart-aware A/B test',
    type: 'Online A/B Test',
    description: '2-week online experiment at 15% of shopping traffic.',
    summary: 'Add-to-cart rate up 7% and revenue per visit up 5%.',
    evaluatedAt: '2026-04-25T09:00:00Z',
    evaluator: 'Growth Analytics',
    metrics: [
      {
        id: 'm-pr-v2-1',
        name: 'Add-to-cart rate',
        value: 4.3,
        unit: '%',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-04-25T09:00:00Z',
      },
      {
        id: 'm-pr-v2-2',
        name: 'Revenue per visit',
        value: 2.29,
        unit: '$',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-04-25T09:00:00Z',
      },
      {
        id: 'm-pr-v2-3',
        name: 'Recall@10',
        value: 0.78,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-04-25T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-pr-v1',
    modelId: 'product-recs',
    versionId: 'product-recs-v1',
    name: 'Product personalization benchmark',
    type: 'Offline Benchmark',
    description: 'Held-out comparison against best-seller ordering.',
    summary: 'Personalized ranker beats best sellers on add-to-cart rate.',
    evaluatedAt: '2026-01-30T09:00:00Z',
    evaluator: 'Arjun Rao',
    metrics: [
      {
        id: 'm-pr-v1-1',
        name: 'Add-to-cart rate',
        value: 3.9,
        unit: '%',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-01-30T09:00:00Z',
      },
      {
        id: 'm-pr-v1-2',
        name: 'Recall@10',
        value: 0.71,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-01-30T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-ca-v2',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v2',
    name: 'Answer quality human review',
    type: 'Human Review',
    description:
      'Support leads rated 500 answers for helpfulness and accuracy.',
    summary: 'Helpfulness 4.4/5 and resolution rate 68%.',
    evaluatedAt: '2026-05-13T09:00:00Z',
    evaluator: 'Support Quality Team',
    metrics: [
      {
        id: 'm-ca-v2-1',
        name: 'Helpfulness',
        value: 4.4,
        unit: '/5',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-05-13T09:00:00Z',
      },
      {
        id: 'm-ca-v2-2',
        name: 'Resolution rate',
        value: 68,
        unit: '%',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-05-13T09:00:00Z',
      },
      {
        id: 'm-ca-v2-3',
        name: 'Response time',
        value: 2.4,
        unit: 's',
        direction: 'lower-is-better',
        category: 'performance',
        measuredAt: '2026-05-13T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-ca-v1',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v1',
    name: 'Deflection human review',
    type: 'Human Review',
    description: 'Reviewers rated 300 answers from the first assistant.',
    summary: 'Helpfulness 3.9/5 and resolution rate 56%.',
    evaluatedAt: '2026-02-15T09:00:00Z',
    evaluator: 'Support Quality Team',
    metrics: [
      {
        id: 'm-ca-v1-1',
        name: 'Helpfulness',
        value: 3.9,
        unit: '/5',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-02-15T09:00:00Z',
      },
      {
        id: 'm-ca-v1-2',
        name: 'Resolution rate',
        value: 56,
        unit: '%',
        direction: 'higher-is-better',
        category: 'business',
        measuredAt: '2026-02-15T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-sf-v2',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v2',
    name: 'Phishing offline benchmark',
    type: 'Offline Benchmark',
    description: 'Held-out evaluation on labeled spam and phishing mail.',
    summary: 'Accuracy 98.2% with false positives below 0.3%.',
    evaluatedAt: '2026-04-04T09:00:00Z',
    evaluator: 'Devon Clarke',
    metrics: [
      {
        id: 'm-sf-v2-1',
        name: 'Accuracy',
        value: 98.2,
        unit: '%',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-04-04T09:00:00Z',
      },
      {
        id: 'm-sf-v2-2',
        name: 'Precision',
        value: 0.97,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-04-04T09:00:00Z',
      },
      {
        id: 'm-sf-v2-3',
        name: 'False-positive rate',
        value: 0.3,
        unit: '%',
        direction: 'lower-is-better',
        category: 'quality',
        measuredAt: '2026-04-04T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-sf-v1',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v1',
    name: 'Spam classifier benchmark',
    type: 'Offline Benchmark',
    description: 'Held-out comparison against the rule-based filter.',
    summary: 'Learned classifier beats rules at 96.4% accuracy.',
    evaluatedAt: '2025-12-18T09:00:00Z',
    evaluator: 'Devon Clarke',
    metrics: [
      {
        id: 'm-sf-v1-1',
        name: 'Accuracy',
        value: 96.4,
        unit: '%',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2025-12-18T09:00:00Z',
      },
      {
        id: 'm-sf-v1-2',
        name: 'False-positive rate',
        value: 0.6,
        unit: '%',
        direction: 'lower-is-better',
        category: 'quality',
        measuredAt: '2025-12-18T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-cm-v2',
    modelId: 'content-mod',
    versionId: 'content-mod-v2',
    name: 'Multimodal moderation benchmark',
    type: 'Offline Benchmark',
    description: 'Held-out evaluation covering text and image violations.',
    summary: 'Recall 0.91 with false-positive rate down to 1.1%.',
    evaluatedAt: '2026-05-03T09:00:00Z',
    evaluator: 'Sofia Alvarez',
    metrics: [
      {
        id: 'm-cm-v2-1',
        name: 'Precision',
        value: 0.9,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-05-03T09:00:00Z',
      },
      {
        id: 'm-cm-v2-2',
        name: 'Recall',
        value: 0.91,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-05-03T09:00:00Z',
      },
      {
        id: 'm-cm-v2-3',
        name: 'False-positive rate',
        value: 1.1,
        unit: '%',
        direction: 'lower-is-better',
        category: 'quality',
        measuredAt: '2026-05-03T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-cm-v1',
    modelId: 'content-mod',
    versionId: 'content-mod-v1',
    name: 'Text moderation benchmark',
    type: 'Offline Benchmark',
    description: 'Held-out evaluation of the first text moderator.',
    summary: 'Recall 0.79 at precision 0.86 on text posts.',
    evaluatedAt: '2026-01-23T09:00:00Z',
    evaluator: 'Sofia Alvarez',
    metrics: [
      {
        id: 'm-cm-v1-1',
        name: 'Precision',
        value: 0.86,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-01-23T09:00:00Z',
      },
      {
        id: 'm-cm-v1-2',
        name: 'Recall',
        value: 0.79,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-01-23T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-ac-v2',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v2',
    name: 'Noisy audio benchmark',
    type: 'Offline Benchmark',
    description: 'Word error rate on real-world noisy recordings.',
    summary: 'Word error rate cut from 9.4% to 6.1% on noisy audio.',
    evaluatedAt: '2026-05-11T09:00:00Z',
    evaluator: 'Liam Nguyen',
    metrics: [
      {
        id: 'm-ac-v2-1',
        name: 'Word error rate',
        value: 6.1,
        unit: '%',
        direction: 'lower-is-better',
        category: 'quality',
        measuredAt: '2026-05-11T09:00:00Z',
      },
      {
        id: 'm-ac-v2-2',
        name: 'Accuracy',
        value: 93.9,
        unit: '%',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-05-11T09:00:00Z',
      },
      {
        id: 'm-ac-v2-3',
        name: 'Latency',
        value: 250,
        unit: 'ms',
        direction: 'lower-is-better',
        category: 'performance',
        measuredAt: '2026-05-11T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-ac-v1',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v1',
    name: 'Clean audio benchmark',
    type: 'Offline Benchmark',
    description: 'Word error rate on clean studio recordings.',
    summary: 'Word error rate 9.4% on clean audio.',
    evaluatedAt: '2026-02-27T09:00:00Z',
    evaluator: 'Liam Nguyen',
    metrics: [
      {
        id: 'm-ac-v1-1',
        name: 'Word error rate',
        value: 9.4,
        unit: '%',
        direction: 'lower-is-better',
        category: 'quality',
        measuredAt: '2026-02-27T09:00:00Z',
      },
      {
        id: 'm-ac-v1-2',
        name: 'Accuracy',
        value: 90.6,
        unit: '%',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-02-27T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-ps-v2',
    modelId: 'photo-search',
    versionId: 'photo-search-v2',
    name: 'Text-to-image benchmark',
    type: 'Offline Benchmark',
    description: 'Recall on typed queries against a held-out photo set.',
    summary: 'Recall@5 of 0.82 at 22ms per lookup.',
    evaluatedAt: '2026-05-06T09:00:00Z',
    evaluator: 'Hannah Kim',
    metrics: [
      {
        id: 'm-ps-v2-1',
        name: 'Recall@5',
        value: 0.82,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-05-06T09:00:00Z',
      },
      {
        id: 'm-ps-v2-2',
        name: 'Precision@5',
        value: 0.74,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-05-06T09:00:00Z',
      },
      {
        id: 'm-ps-v2-3',
        name: 'Latency',
        value: 22,
        unit: 'ms',
        direction: 'lower-is-better',
        category: 'performance',
        measuredAt: '2026-05-06T09:00:00Z',
      },
    ],
  },
  {
    id: 'ev-ps-v1',
    modelId: 'photo-search',
    versionId: 'photo-search-v1',
    name: 'Similar-photo benchmark',
    type: 'Offline Benchmark',
    description: 'Recall on example-image queries against a held-out set.',
    summary: 'Recall@5 of 0.73 with image embeddings.',
    evaluatedAt: '2026-03-09T09:00:00Z',
    evaluator: 'Hannah Kim',
    metrics: [
      {
        id: 'm-ps-v1-1',
        name: 'Recall@5',
        value: 0.73,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-03-09T09:00:00Z',
      },
      {
        id: 'm-ps-v1-2',
        name: 'Precision@5',
        value: 0.66,
        unit: '',
        direction: 'higher-is-better',
        category: 'quality',
        measuredAt: '2026-03-09T09:00:00Z',
      },
    ],
  },
]

export const mockDeployments: Deployment[] = [
  {
    id: 'dep-vr-v2',
    modelId: 'video-recs',
    versionId: 'video-recs-v2',
    name: 'video-feed-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/video-recs/v2',
    region: 'us-east-1',
    deployedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'dep-vr-v1',
    modelId: 'video-recs',
    versionId: 'video-recs-v1',
    name: 'video-feed-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/video-recs/v1',
    region: 'us-east-1',
    deployedAt: '2026-02-01T09:00:00Z',
    rolledBackAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'dep-pr-v2',
    modelId: 'product-recs',
    versionId: 'product-recs-v2',
    name: 'product-recs-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/product-recs/v2',
    region: 'us-east-1',
    deployedAt: '2026-04-28T09:00:00Z',
  },
  {
    id: 'dep-pr-v1',
    modelId: 'product-recs',
    versionId: 'product-recs-v1',
    name: 'product-recs-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/product-recs/v1',
    region: 'us-east-1',
    deployedAt: '2026-02-08T09:00:00Z',
    rolledBackAt: '2026-04-28T09:00:00Z',
  },
  {
    id: 'dep-ca-v2',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v2',
    name: 'support-chat-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/support-chat/v2',
    region: 'us-east-1',
    deployedAt: '2026-05-18T09:00:00Z',
  },
  {
    id: 'dep-ca-v1',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v1',
    name: 'support-chat-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/support-chat/v1',
    region: 'us-east-1',
    deployedAt: '2026-02-22T09:00:00Z',
    rolledBackAt: '2026-05-18T09:00:00Z',
  },
  {
    id: 'dep-sf-v2',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v2',
    name: 'spam-filter-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/spam-filter/v2',
    region: 'us-east-1',
    deployedAt: '2026-04-14T09:00:00Z',
  },
  {
    id: 'dep-sf-v1',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v1',
    name: 'spam-filter-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/spam-filter/v1',
    region: 'us-east-1',
    deployedAt: '2025-12-28T09:00:00Z',
    rolledBackAt: '2026-04-14T09:00:00Z',
  },
  {
    id: 'dep-cm-v2',
    modelId: 'content-mod',
    versionId: 'content-mod-v2',
    name: 'moderation-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/moderation/v2',
    region: 'us-east-1',
    deployedAt: '2026-05-06T09:00:00Z',
  },
  {
    id: 'dep-cm-v1',
    modelId: 'content-mod',
    versionId: 'content-mod-v1',
    name: 'moderation-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/moderation/v1',
    region: 'us-east-1',
    deployedAt: '2026-01-30T09:00:00Z',
    rolledBackAt: '2026-05-06T09:00:00Z',
  },
  {
    id: 'dep-ac-v2',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v2',
    name: 'captions-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/captions/v2',
    region: 'us-east-1',
    deployedAt: '2026-05-14T09:00:00Z',
  },
  {
    id: 'dep-ac-v1',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v1',
    name: 'captions-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/captions/v1',
    region: 'us-east-1',
    deployedAt: '2026-03-06T09:00:00Z',
    rolledBackAt: '2026-05-14T09:00:00Z',
  },
  {
    id: 'dep-ps-v2',
    modelId: 'photo-search',
    versionId: 'photo-search-v2',
    name: 'photo-search-prod',
    environment: 'production',
    status: 'live',
    endpoint: 'https://infer.internal/photo-search/v2',
    region: 'us-east-1',
    deployedAt: '2026-05-09T09:00:00Z',
  },
  {
    id: 'dep-ps-v1',
    modelId: 'photo-search',
    versionId: 'photo-search-v1',
    name: 'photo-search-prod',
    environment: 'production',
    status: 'rolled-back',
    endpoint: 'https://infer.internal/photo-search/v1',
    region: 'us-east-1',
    deployedAt: '2026-03-12T09:00:00Z',
    rolledBackAt: '2026-05-09T09:00:00Z',
  },
]

export const mockFindings: Finding[] = [
  {
    id: 'f-vr-v2',
    modelId: 'video-recs',
    versionId: 'video-recs-v2',
    title: 'Session context lifts watch time',
    summary: 'Adding session context raised average watch time 12%.',
    description:
      'Runs r-vr-v2-a and r-vr-v2-b show the biggest gains for viewers with short histories, where session signals fill the gap. Recommend promoting v2 to the full home feed.',
    severity: 'high',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Maya Patel',
    createdAt: '2026-04-19T09:00:00Z',
    runIds: ['r-vr-v2-a', 'r-vr-v2-b'],
    linkedVersionId: 'video-recs-v2',
    pinned: true,
  },
  {
    id: 'f-vr-v1',
    modelId: 'video-recs',
    versionId: 'video-recs-v1',
    title: 'Personalization beats popularity',
    summary: 'Personalized feed lifted click-through rate over most-popular.',
    description:
      'Run r-vr-v1-b improved click-through rate from 4.8% to 5.9% versus the popularity baseline r-vr-v1-a. Establishes personalization as the default feed.',
    severity: 'medium',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Maya Patel',
    createdAt: '2026-01-26T09:00:00Z',
    runIds: ['r-vr-v1-a', 'r-vr-v1-b'],
    linkedVersionId: 'video-recs-v1',
    pinned: false,
  },
  {
    id: 'f-pr-v2',
    modelId: 'product-recs',
    versionId: 'product-recs-v2',
    title: 'Cart context raises revenue per visit',
    summary: 'Reacting to cart contents lifted revenue per visit 5%.',
    description:
      'Run r-pr-v2-b shows the model recommends complementary items once something is in the cart, raising add-to-cart rate and revenue per visit. Recommend promotion.',
    severity: 'high',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Arjun Rao',
    createdAt: '2026-04-13T09:00:00Z',
    runIds: ['r-pr-v2-a', 'r-pr-v2-b'],
    linkedVersionId: 'product-recs-v2',
    pinned: true,
  },
  {
    id: 'f-pr-v1',
    modelId: 'product-recs',
    versionId: 'product-recs-v1',
    title: 'Purchase history beats best sellers',
    summary: 'Personalized ranker lifted add-to-cart rate over best sellers.',
    description:
      'Run r-pr-v1-b raised add-to-cart rate from 3.1% to 3.9% versus the best-seller baseline. Establishes personalization for the product feed.',
    severity: 'medium',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Arjun Rao',
    createdAt: '2026-01-31T09:00:00Z',
    runIds: ['r-pr-v1-a', 'r-pr-v1-b'],
    linkedVersionId: 'product-recs-v1',
    pinned: false,
  },
  {
    id: 'f-ca-v2',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v2',
    title: 'Grounding cuts wrong answers',
    summary: 'Retrieval grounding raised resolution rate to 68%.',
    description:
      'Run r-ca-v2-b cites help-center articles, which reviewers found reduced confidently-wrong answers and improved helpfulness to 4.4/5. Recommend promotion.',
    severity: 'high',
    status: 'published',
    source: 'Human review',
    author: 'Priya Nair',
    createdAt: '2026-05-12T09:00:00Z',
    runIds: ['r-ca-v2-a', 'r-ca-v2-b'],
    linkedVersionId: 'chat-assistant-v2',
    pinned: true,
  },
  {
    id: 'f-ca-v1',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v1',
    title: 'Fine-tuning improves deflection',
    summary: 'Fine-tuning on past chats raised resolution rate to 56%.',
    description:
      'Run r-ca-v1-b beat the prompted baseline on helpfulness and resolution, but reviewers flagged occasional wrong answers, motivating retrieval grounding in v2.',
    severity: 'medium',
    status: 'published',
    source: 'Human review',
    author: 'Priya Nair',
    createdAt: '2026-02-16T09:00:00Z',
    runIds: ['r-ca-v1-a', 'r-ca-v1-b'],
    linkedVersionId: 'chat-assistant-v1',
    pinned: false,
  },
  {
    id: 'f-sf-v2',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v2',
    title: 'Link features catch phishing',
    summary: 'Phishing recall up 14 points with link and sender features.',
    description:
      'Run r-sf-v2-b uses link reputation and sender scores to catch phishing the text-only model missed, while false positives fell below 0.3%. Recommend promotion.',
    severity: 'high',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Devon Clarke',
    createdAt: '2026-04-03T09:00:00Z',
    runIds: ['r-sf-v2-a', 'r-sf-v2-b'],
    linkedVersionId: 'spam-filter-v2',
    pinned: true,
  },
  {
    id: 'f-sf-v1',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v1',
    title: 'Learned filter beats hand-written rules',
    summary: 'Classifier reached 96.4% accuracy versus 92.1% for rules.',
    description:
      'Run r-sf-v1-b outperformed the rule engine on accuracy and false positives, retiring hundreds of brittle hand-written rules.',
    severity: 'medium',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Devon Clarke',
    createdAt: '2025-12-19T09:00:00Z',
    runIds: ['r-sf-v1-a', 'r-sf-v1-b'],
    linkedVersionId: 'spam-filter-v1',
    pinned: false,
  },
  {
    id: 'f-cm-v2',
    modelId: 'content-mod',
    versionId: 'content-mod-v2',
    title: 'Image review catches hidden violations',
    summary: 'Multimodal model raised recall to 0.91 on image posts.',
    description:
      'Run r-cm-v2-b reviews attached images, catching violations the text-only model missed, while lowering the false-positive rate. Recommend promotion.',
    severity: 'high',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Sofia Alvarez',
    createdAt: '2026-05-03T09:00:00Z',
    runIds: ['r-cm-v2-a', 'r-cm-v2-b'],
    linkedVersionId: 'content-mod-v2',
    pinned: true,
  },
  {
    id: 'f-cm-v1',
    modelId: 'content-mod',
    versionId: 'content-mod-v1',
    title: 'Text classifier beats keyword blocklist',
    summary: 'Learned moderator raised recall from 0.61 to 0.79.',
    description:
      'Run r-cm-v1-b caught paraphrased violations the keyword blocklist missed, cutting false positives from 3.4% to 1.6%.',
    severity: 'medium',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Sofia Alvarez',
    createdAt: '2026-01-24T09:00:00Z',
    runIds: ['r-cm-v1-a', 'r-cm-v1-b'],
    linkedVersionId: 'content-mod-v1',
    pinned: false,
  },
  {
    id: 'f-ac-v2',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v2',
    title: 'Noise training fixes real-world audio',
    summary: 'Word error rate fell from 9.4% to 6.1% on noisy clips.',
    description:
      'Run r-ac-v2-b trains with background noise and overlapping speakers, which closes most of the gap on real calls at a small latency cost. Recommend promotion.',
    severity: 'high',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Liam Nguyen',
    createdAt: '2026-05-10T09:00:00Z',
    runIds: ['r-ac-v2-a', 'r-ac-v2-b'],
    linkedVersionId: 'auto-captions-v2',
    pinned: true,
  },
  {
    id: 'f-ac-v1',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v1',
    title: 'Captions usable on clean audio only',
    summary: 'Word error rate jumps sharply once background noise appears.',
    description:
      'Run r-ac-v1-b reaches 9.4% word error rate on clean studio audio but degrades on noisy recordings, motivating the noise-augmentation work in v2.',
    severity: 'medium',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Liam Nguyen',
    createdAt: '2026-02-28T09:00:00Z',
    runIds: ['r-ac-v1-a', 'r-ac-v1-b'],
    linkedVersionId: 'auto-captions-v1',
    pinned: false,
  },
  {
    id: 'f-ps-v2',
    modelId: 'photo-search',
    versionId: 'photo-search-v2',
    title: 'Typed queries now find the right photos',
    summary: 'Text-to-image search reached recall@5 of 0.82.',
    description:
      'Run r-ps-v2-b learns a shared text-image embedding so people can search photos by description. Recall@5 rose to 0.82 with lookups still around 22ms. Recommend promotion.',
    severity: 'high',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Hannah Kim',
    createdAt: '2026-05-05T09:00:00Z',
    runIds: ['r-ps-v2-a', 'r-ps-v2-b'],
    linkedVersionId: 'photo-search-v2',
    pinned: true,
  },
  {
    id: 'f-ps-v1',
    modelId: 'photo-search',
    versionId: 'photo-search-v1',
    title: 'Embeddings beat color matching',
    summary: 'Learned image embeddings raised recall@5 to 0.73.',
    description:
      'Run r-ps-v1-b replaced color-histogram matching with learned embeddings, improving similar-photo recall from 0.58 to 0.73.',
    severity: 'medium',
    status: 'published',
    source: 'Experiment analysis',
    author: 'Hannah Kim',
    createdAt: '2026-03-10T09:00:00Z',
    runIds: ['r-ps-v1-a', 'r-ps-v1-b'],
    linkedVersionId: 'photo-search-v1',
    pinned: false,
  },
]

export const mockDecisions: Decision[] = [
  {
    id: 'dc-vr-v2',
    modelId: 'video-recs',
    versionId: 'video-recs-v2',
    title: 'Promote Video Recs v2 to production',
    decision: 'Ship v2 to 100% of home-feed traffic.',
    reason: 'A/B test showed +9% click-through rate and +12% watch time.',
    impact: 'Better recommendations for new viewers; retires v1.',
    decisionMaker: 'Maya Patel',
    decidedAt: '2026-04-30T09:00:00Z',
  },
  {
    id: 'dc-vr-v1',
    modelId: 'video-recs',
    versionId: 'video-recs-v1',
    title: 'Launch the personalized feed',
    decision: 'Replace most-popular ordering with the personalized feed.',
    reason: 'Personalization beat popularity on click-through rate offline.',
    impact: 'Establishes the personalized feed as the default.',
    decisionMaker: 'Maya Patel',
    decidedAt: '2026-01-30T09:00:00Z',
  },
  {
    id: 'dc-pr-v2',
    modelId: 'product-recs',
    versionId: 'product-recs-v2',
    title: 'Promote Product Recs v2 to production',
    decision: 'Ship the cart-aware ranker to all shopping traffic.',
    reason: 'A/B test showed +7% add-to-cart rate and +5% revenue per visit.',
    impact: 'More relevant product suggestions; retires v1.',
    decisionMaker: 'Arjun Rao',
    decidedAt: '2026-04-26T09:00:00Z',
  },
  {
    id: 'dc-pr-v1',
    modelId: 'product-recs',
    versionId: 'product-recs-v1',
    title: 'Launch personalized product feed',
    decision: 'Replace best-seller ordering with the personalized ranker.',
    reason: 'Personalization beat best sellers on add-to-cart rate.',
    impact: 'Establishes personalization for the store feed.',
    decisionMaker: 'Arjun Rao',
    decidedAt: '2026-02-05T09:00:00Z',
  },
  {
    id: 'dc-ca-v2',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v2',
    title: 'Promote grounded assistant to production',
    decision: 'Ship the retrieval-grounded assistant to the help center.',
    reason: 'Grounding raised resolution rate to 68% and cut wrong answers.',
    impact: 'Fewer escalations to human agents; retires v1.',
    decisionMaker: 'Priya Nair',
    decidedAt: '2026-05-16T09:00:00Z',
  },
  {
    id: 'dc-ca-v1',
    modelId: 'chat-assistant',
    versionId: 'chat-assistant-v1',
    title: 'Launch the first support assistant',
    decision: 'Deploy the fine-tuned assistant for routine questions.',
    reason: 'Fine-tuning reached 56% resolution on common questions.',
    impact: 'Deflects routine questions; wrong answers flagged for v2.',
    decisionMaker: 'Priya Nair',
    decidedAt: '2026-02-20T09:00:00Z',
  },
  {
    id: 'dc-sf-v2',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v2',
    title: 'Promote Spam Filter v2 to production',
    decision: 'Ship the phishing-aware filter to all inboxes.',
    reason: 'Phishing recall up 14 points with false positives below 0.3%.',
    impact: 'Fewer phishing emails reach users; retires v1.',
    decisionMaker: 'Devon Clarke',
    decidedAt: '2026-04-12T09:00:00Z',
  },
  {
    id: 'dc-sf-v1',
    modelId: 'spam-filter',
    versionId: 'spam-filter-v1',
    title: 'Replace spam rules with a classifier',
    decision: 'Retire hand-written rules for the learned classifier.',
    reason: 'The classifier beat rules on accuracy and false positives.',
    impact: 'Simpler, more accurate spam filtering.',
    decisionMaker: 'Devon Clarke',
    decidedAt: '2025-12-24T09:00:00Z',
  },
  {
    id: 'dc-cm-v2',
    modelId: 'content-mod',
    versionId: 'content-mod-v2',
    title: 'Promote multimodal moderation to production',
    decision: 'Ship the image + text moderation model.',
    reason: 'Recall rose to 0.91 with fewer false removals.',
    impact: 'Catches image-based violations; retires the text-only model.',
    decisionMaker: 'Sofia Alvarez',
    decidedAt: '2026-05-04T09:00:00Z',
  },
  {
    id: 'dc-cm-v1',
    modelId: 'content-mod',
    versionId: 'content-mod-v1',
    title: 'Launch automated text moderation',
    decision: 'Replace the keyword blocklist with the learned moderator.',
    reason: 'The classifier caught paraphrased violations with fewer errors.',
    impact: 'Automates most text-policy removals.',
    decisionMaker: 'Sofia Alvarez',
    decidedAt: '2026-01-27T09:00:00Z',
  },
  {
    id: 'dc-ac-v2',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v2',
    title: 'Promote noise-robust captions to production',
    decision: 'Ship the noise-augmented caption model.',
    reason: 'Word error rate fell from 9.4% to 6.1% on real recordings.',
    impact: 'Usable captions on noisy calls; retires v1.',
    decisionMaker: 'Liam Nguyen',
    decidedAt: '2026-05-12T09:00:00Z',
  },
  {
    id: 'dc-ac-v1',
    modelId: 'auto-captions',
    versionId: 'auto-captions-v1',
    title: 'Launch captions for clean audio',
    decision: 'Deploy the caption model for studio-quality recordings.',
    reason: 'Reached under 10% word error rate on clean audio.',
    impact: 'Ships live captions; noisy audio deferred to v2.',
    decisionMaker: 'Liam Nguyen',
    decidedAt: '2026-03-04T09:00:00Z',
  },
  {
    id: 'dc-ps-v2',
    modelId: 'photo-search',
    versionId: 'photo-search-v2',
    title: 'Promote text-to-image search to production',
    decision: 'Ship the shared text-image embedding for photo search.',
    reason: 'Recall@5 reached 0.82 at 22ms per lookup.',
    impact: 'People can search photos by description; retires v1.',
    decisionMaker: 'Hannah Kim',
    decidedAt: '2026-05-07T09:00:00Z',
  },
  {
    id: 'dc-ps-v1',
    modelId: 'photo-search',
    versionId: 'photo-search-v1',
    title: 'Launch similar-photo search',
    decision: 'Replace color-histogram matching with learned embeddings.',
    reason: 'Embeddings raised recall@5 from 0.58 to 0.73.',
    impact: 'Better similar-photo results.',
    decisionMaker: 'Hannah Kim',
    decidedAt: '2026-03-11T09:00:00Z',
  },
]
