import type {
  Service,
  ServiceComment,
  ServiceConfig,
  ServiceDataSchema,
  ServiceDiagram,
  ServiceEndpoint,
  ServiceJob,
  ServiceOwner,
} from '../types'

export const mockServices: Service[] = [
  {
    id: 'user-service',
    name: 'User Service',
    domain: 'auth.example.com',
    team: 'Platform Team',
    environment: 'production' as const,
    status: 'healthy' as const,
    description:
      'Handles user authentication and profile management with OAuth2 and JWT tokens',
    endpoints: 12,
    lastDeployed: '2024-10-20T10:30:00Z',
    uptime: '99.9%',
    domainArea: 'Auth',
    tags: ['REST', 'OAuth2', 'Critical'],
    updatedBy: 'Alice Chen',
    specLinked: true,
    diagramCount: 2,
    repository: 'https://github.com/company/user-service',
  },
  {
    id: 'payment-service',
    name: 'Payment Service',
    domain: 'payments.example.com',
    team: 'Marketplace',
    environment: 'production' as const,
    status: 'healthy' as const,
    description:
      'Processes payments, refunds, and manages billing cycles for all transactions',
    endpoints: 18,
    lastDeployed: '2024-10-18T15:45:00Z',
    uptime: '99.8%',
    domainArea: 'Payments',
    tags: ['Events', 'Stripe', 'PCI'],
    updatedBy: 'Bob Smith',
    specCoverage: {
      covered: 18,
      total: 18,
    },
    diagramCount: 3,
  },
  {
    id: 'notification-service',
    name: 'Notification Service',
    domain: 'notifications.example.com',
    team: 'Platform Team',
    environment: 'production' as const,
    status: 'degraded' as const,
    description:
      'Sends emails, SMS, and push notifications across multiple channels',
    endpoints: 6,
    lastDeployed: '2024-10-15T09:20:00Z',
    uptime: '98.5%',
    domainArea: 'Messaging',
    tags: ['Events', 'SQS', 'SNS'],
    updatedBy: 'Carol Lee',
    specLinked: true,
  },
  {
    id: 'analytics-service',
    name: 'Analytics Service',
    domain: 'analytics.example.com',
    team: 'Data Team',
    environment: 'staging' as const,
    status: 'healthy' as const,
    description:
      'Collects and processes user analytics data with real-time dashboards',
    endpoints: 15,
    lastDeployed: '2024-10-22T14:10:00Z',
    uptime: '99.7%',
    domainArea: 'Analytics',
    tags: ['GraphQL', 'Kafka', 'Postgres'],
    updatedBy: 'David Park',
    specCoverage: {
      covered: 12,
      total: 15,
    },
  },
  {
    id: 'inventory-service',
    name: 'Inventory Service',
    domain: 'inventory.example.com',
    team: 'Operations',
    environment: 'production' as const,
    status: 'healthy' as const,
    description: 'Manages product inventory and stock levels',
    endpoints: 8,
    lastDeployed: '2024-10-19T11:00:00Z',
    uptime: '99.9%',
    domainArea: 'Operations',
    tags: ['REST', 'DynamoDB'],
    updatedBy: 'Eve Martinez',
    diagramCount: 1,
  },
  {
    id: 'search-service',
    name: 'Search Service',
    domain: 'search.example.com',
    team: 'Core',
    environment: 'production' as const,
    status: 'healthy' as const,
    description: 'Provides full-text search capabilities',
    endpoints: 4,
    lastDeployed: '2024-10-21T16:30:00Z',
    uptime: '99.95%',
    domainArea: 'Core',
    tags: ['Elasticsearch', 'Lambda'],
    updatedBy: 'Frank Wilson',
  },
]

export const mockService = {
  id: 'user-service',
  name: 'User Service',
  domain: 'auth.example.com',
  team: 'Platform Team',
  environment: 'production' as const,
  status: 'healthy' as const,
  description: 'Handles user authentication and profile management',
  endpoints: 12,
  lastDeployed: '2024-01-15T10:30:00Z',
  uptime: '99.9%',
  tags: ['api', 'microservice', 'critical'],
  owner: 'John Doe',
  repository: 'https://github.com/company/user-service',
  documentation: 'https://docs.example.com/user-service',
}

export const mockOverviewData = {
  service: {
    id: 'user-service',
    name: 'User Service',
    description:
      'Handles user authentication and profile management with OAuth2 and JWT tokens. Provides secure session management and user data access.',
    domain: 'Auth',
    team: 'Platform Team',
    tags: ['REST', 'OAuth2', 'Critical'],
    repository: 'https://github.com/company/user-service',
    owner: {
      name: 'Alice Chen',
      avatar: 'AC',
    },
    defaultEnvironments: ['production', 'staging'],
  },
  deployment: {
    version: 'v2.1.0',
    lastUpdated: '2024-01-15T10:30:00Z',
    updatedBy: 'Alice Chen',
  },
  artifacts: {
    endpoints: 12,
    diagrams: 2,
    techSpecs: 1,
    tests: 8,
  },
  relationships: {
    connectedServices: 5,
  },
  techSpec: {
    preview:
      'The User Service is the central authentication and authorization system for the platform. It implements OAuth2 and JWT-based authentication, manages user sessions, and provides secure access to user profile data...',
    url: '/docs/user-service-spec',
  },
  recentChanges: [
    {
      id: '1',
      type: 'openapi',
      description: 'Imported 3 endpoints from OpenAPI spec',
      actor: 'Bob Smith',
      date: '2024-01-15T10:30:00Z',
    },
    {
      id: '2',
      type: 'schema',
      description: 'Updated database schema documentation',
      actor: 'Alice Chen',
      date: '2024-01-14T15:20:00Z',
    },
    {
      id: '3',
      type: 'diagram',
      description: 'Added authentication flow diagram',
      actor: 'Carol Lee',
      date: '2024-01-13T09:15:00Z',
    },
  ],
}

export const mockEndpoints = [
  {
    id: '1',
    method: 'GET',
    path: '/api/v1/users',
    description: 'List all users with pagination and filtering',
    auth: 'bearer',
    tags: ['users', 'public', 'v1'],
    statusCodes: [200, 400, 401, 403, 500],
    updated: '2024-01-15T10:30:00Z',
    updatedBy: 'Alice Chen',
    links: {
      logic: 2,
      samples: 3,
      tests: 1,
      flow: true,
    },
    badges: ['modified'],
    sourceFile: 'src/handlers/users.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '2',
    method: 'POST',
    path: '/api/v1/users',
    description: 'Create a new user account',
    auth: 'bearer',
    tags: ['users', 'write'],
    statusCodes: [201, 400, 401, 409],
    updated: '2024-01-14T15:20:00Z',
    updatedBy: 'Bob Smith',
    links: {
      logic: 1,
      samples: 2,
      tests: 2,
      flow: false,
    },
    badges: ['new'],
    sourceFile: 'src/handlers/users.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '3',
    method: 'GET',
    path: '/api/v1/users/{id}',
    description: 'Get user details by ID',
    auth: 'bearer',
    tags: ['users', 'public'],
    statusCodes: [200, 401, 404],
    updated: '2024-01-13T09:15:00Z',
    updatedBy: 'Carol Lee',
    links: {
      logic: 1,
      samples: 1,
      tests: 0,
      flow: true,
    },
    badges: [],
    sourceFile: 'src/handlers/users.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '4',
    method: 'PATCH',
    path: '/api/v1/users/{id}',
    description: 'Update partial user profile fields',
    auth: 'bearer',
    tags: ['users', 'write'],
    statusCodes: [200, 400, 401, 403, 404],
    updated: '2024-01-16T12:00:00Z',
    updatedBy: 'Dana White',
    links: {
      logic: 2,
      samples: 2,
      tests: 1,
      flow: false,
    },
    badges: ['modified'],
    sourceFile: 'src/handlers/users.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '5',
    method: 'DELETE',
    path: '/api/v1/users/{id}',
    description: 'Soft delete a user account',
    auth: 'bearer',
    tags: ['users', 'write'],
    statusCodes: [204, 401, 403, 404],
    updated: '2024-01-16T12:05:00Z',
    updatedBy: 'Dana White',
    links: {
      logic: 1,
      samples: 1,
      tests: 1,
      flow: false,
    },
    badges: [],
    sourceFile: 'src/handlers/users.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '6',
    method: 'POST',
    path: '/api/v1/auth/login',
    description: 'Authenticate user and return JWT',
    auth: 'public',
    tags: ['auth'],
    statusCodes: [200, 400, 401, 429],
    updated: '2024-01-12T08:45:00Z',
    updatedBy: 'Alice Chen',
    links: {
      logic: 1,
      samples: 2,
      tests: 2,
      flow: true,
    },
    badges: ['stable'],
    sourceFile: 'src/handlers/auth.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '7',
    method: 'POST',
    path: '/api/v1/auth/refresh',
    description: 'Refresh JWT using refresh token',
    auth: 'bearer',
    tags: ['auth'],
    statusCodes: [200, 400, 401],
    updated: '2024-01-12T09:00:00Z',
    updatedBy: 'Bob Smith',
    links: {
      logic: 1,
      samples: 1,
      tests: 1,
      flow: false,
    },
    badges: [],
    sourceFile: 'src/handlers/auth.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '8',
    method: 'GET',
    path: '/api/v1/groups',
    description: 'List groups with pagination',
    auth: 'bearer',
    tags: ['groups', 'public'],
    statusCodes: [200, 401, 500],
    updated: '2024-01-11T14:10:00Z',
    updatedBy: 'Carol Lee',
    links: {
      logic: 1,
      samples: 1,
      tests: 0,
      flow: false,
    },
    badges: [],
    sourceFile: 'src/handlers/groups.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '9',
    method: 'POST',
    path: '/api/v1/groups',
    description: 'Create a new group',
    auth: 'bearer',
    tags: ['groups', 'write'],
    statusCodes: [201, 400, 401, 409],
    updated: '2024-01-11T14:20:00Z',
    updatedBy: 'Carol Lee',
    links: {
      logic: 1,
      samples: 2,
      tests: 1,
      flow: false,
    },
    badges: ['new'],
    sourceFile: 'src/handlers/groups.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '10',
    method: 'GET',
    path: '/api/v1/groups/{id}',
    description: 'Get group by ID',
    auth: 'bearer',
    tags: ['groups', 'public'],
    statusCodes: [200, 401, 404],
    updated: '2024-01-11T14:25:00Z',
    updatedBy: 'Bob Smith',
    links: {
      logic: 1,
      samples: 1,
      tests: 0,
      flow: false,
    },
    badges: [],
    sourceFile: 'src/handlers/groups.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '11',
    method: 'PUT',
    path: '/api/v1/groups/{id}',
    description: 'Replace group details',
    auth: 'bearer',
    tags: ['groups', 'write'],
    statusCodes: [200, 400, 401, 403, 404],
    updated: '2024-01-11T14:35:00Z',
    updatedBy: 'Dana White',
    links: {
      logic: 2,
      samples: 1,
      tests: 1,
      flow: false,
    },
    badges: ['modified'],
    sourceFile: 'src/handlers/groups.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '12',
    method: 'DELETE',
    path: '/api/v1/groups/{id}',
    description: 'Delete a group',
    auth: 'bearer',
    tags: ['groups', 'write'],
    statusCodes: [204, 401, 403, 404],
    updated: '2024-01-11T14:40:00Z',
    updatedBy: 'Dana White',
    links: {
      logic: 1,
      samples: 1,
      tests: 1,
      flow: false,
    },
    badges: [],
    sourceFile: 'src/handlers/groups.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '13',
    method: 'GET',
    path: '/api/v1/users/search',
    description: 'Search users by query and filters',
    auth: 'bearer',
    tags: ['users', 'search'],
    statusCodes: [200, 400, 401, 429],
    updated: '2024-01-17T09:10:00Z',
    updatedBy: 'Alice Chen',
    links: { logic: 2, samples: 2, tests: 1, flow: false },
    badges: [],
    sourceFile: 'src/handlers/users-search.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '14',
    method: 'POST',
    path: '/api/v1/users/export',
    description: 'Export users as CSV asynchronously',
    auth: 'bearer',
    tags: ['users', 'export'],
    statusCodes: [202, 400, 401, 403],
    updated: '2024-01-17T09:20:00Z',
    updatedBy: 'Bob Smith',
    links: { logic: 2, samples: 1, tests: 1, flow: true },
    badges: ['beta'],
    sourceFile: 'src/handlers/users-export.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '15',
    method: 'POST',
    path: '/api/v1/auth/password-reset',
    description: 'Request password reset email',
    auth: 'public',
    tags: ['auth'],
    statusCodes: [204, 400, 404, 429],
    updated: '2024-01-10T10:00:00Z',
    updatedBy: 'Carol Lee',
    links: { logic: 1, samples: 1, tests: 1, flow: false },
    badges: [],
    sourceFile: 'src/handlers/password.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '16',
    method: 'POST',
    path: '/api/v1/auth/password-reset/confirm',
    description: 'Confirm password reset with token',
    auth: 'public',
    tags: ['auth'],
    statusCodes: [204, 400, 410],
    updated: '2024-01-10T10:10:00Z',
    updatedBy: 'Carol Lee',
    links: { logic: 1, samples: 1, tests: 2, flow: false },
    badges: ['stable'],
    sourceFile: 'src/handlers/password.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '17',
    method: 'POST',
    path: '/api/v1/auth/mfa/enable',
    description: 'Enable MFA for current user',
    auth: 'bearer',
    tags: ['auth', 'mfa'],
    statusCodes: [200, 401, 409],
    updated: '2024-01-09T12:00:00Z',
    updatedBy: 'Dana White',
    links: { logic: 1, samples: 1, tests: 1, flow: true },
    badges: [],
    sourceFile: 'src/handlers/mfa.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '18',
    method: 'POST',
    path: '/api/v1/auth/mfa/verify',
    description: 'Verify MFA challenge',
    auth: 'bearer',
    tags: ['auth', 'mfa'],
    statusCodes: [204, 400, 401],
    updated: '2024-01-09T12:05:00Z',
    updatedBy: 'Dana White',
    links: { logic: 1, samples: 1, tests: 1, flow: false },
    badges: [],
    sourceFile: 'src/handlers/mfa.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '19',
    method: 'GET',
    path: '/api/v1/audit/logs',
    description: 'List audit logs with filters',
    auth: 'bearer',
    tags: ['audit'],
    statusCodes: [200, 400, 401, 403],
    updated: '2024-01-08T16:30:00Z',
    updatedBy: 'Alice Chen',
    links: { logic: 1, samples: 1, tests: 0, flow: false },
    badges: [],
    sourceFile: 'src/handlers/audit.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '20',
    method: 'POST',
    path: '/api/v1/users/{id}/avatar',
    description: 'Upload or replace user avatar',
    auth: 'bearer',
    tags: ['users', 'media'],
    statusCodes: [201, 400, 401, 413],
    updated: '2024-01-07T11:40:00Z',
    updatedBy: 'Bob Smith',
    links: { logic: 2, samples: 1, tests: 1, flow: false },
    badges: [],
    sourceFile: 'src/handlers/avatar.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '21',
    method: 'GET',
    path: '/api/v1/roles',
    description: 'List available roles',
    auth: 'bearer',
    tags: ['roles', 'public'],
    statusCodes: [200, 401],
    updated: '2024-01-06T10:00:00Z',
    updatedBy: 'Alice Chen',
    links: { logic: 1, samples: 1, tests: 0, flow: false },
    badges: [],
    sourceFile: 'src/handlers/roles.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
  {
    id: '22',
    method: 'PUT',
    path: '/api/v1/users/{id}/roles',
    description: 'Assign roles to a user',
    auth: 'bearer',
    tags: ['roles', 'write'],
    statusCodes: [200, 400, 401, 403, 404],
    updated: '2024-01-06T10:15:00Z',
    updatedBy: 'Bob Smith',
    links: { logic: 2, samples: 1, tests: 1, flow: false },
    badges: ['modified'],
    sourceFile: 'src/handlers/roles.ts',
    sourceRepo: 'https://github.com/company/user-service',
  },
]

export const mockEndpointsServiceEndpoints: ServiceEndpoint[] = [
  {
    id: '1',
    method: 'GET',
    path: '/api/v1/users',
    auth: 'bearer',
    statusCodes: [200, 401, 403, 500],
    tags: ['users', 'public'],
    lastUpdated: '2024-01-15T10:30:00Z',
    sourceFile: 'routes/users.ts',
    description: 'Get all users with pagination',
  },
  {
    id: '2',
    method: 'POST',
    path: '/api/v1/users',
    auth: 'bearer',
    statusCodes: [201, 400, 401, 409, 500],
    tags: ['users', 'admin'],
    lastUpdated: '2024-01-14T15:45:00Z',
    sourceFile: 'routes/users.ts',
    description: 'Create a new user',
  },
  {
    id: '3',
    method: 'GET',
    path: '/api/v1/users/{id}',
    auth: 'bearer',
    statusCodes: [200, 401, 404, 500],
    tags: ['users', 'public'],
    lastUpdated: '2024-01-13T09:20:00Z',
    sourceFile: 'routes/users.ts',
    description: 'Get user by ID',
  },
  {
    id: '4',
    method: 'PUT',
    path: '/api/v1/users/{id}',
    auth: 'bearer',
    statusCodes: [200, 400, 401, 404, 500],
    tags: ['users', 'admin'],
    lastUpdated: '2024-01-12T14:10:00Z',
    sourceFile: 'routes/users.ts',
    description: 'Update user by ID',
  },
  {
    id: '5',
    method: 'DELETE',
    path: '/api/v1/users/{id}',
    auth: 'bearer',
    statusCodes: [204, 401, 404, 500],
    tags: ['users', 'admin'],
    lastUpdated: '2024-01-11T11:30:00Z',
    sourceFile: 'routes/users.ts',
    description: 'Delete user by ID',
  },
]

export const mockDataSchemas: ServiceDataSchema[] = [
  {
    id: '1',
    name: 'users_db',
    type: 'database',
    environment: 'production',
    lastScanned: '2024-01-15T10:30:00Z',
    tables: [
      {
        name: 'users',
        columns: [
          {
            name: 'id',
            type: 'UUID',
            nullable: false,
            description: 'Primary key',
          },
          {
            name: 'email',
            type: 'VARCHAR(255)',
            nullable: false,
            description: 'User email address',
          },
          {
            name: 'password_hash',
            type: 'VARCHAR(255)',
            nullable: false,
            description: 'Hashed password',
          },
          {
            name: 'first_name',
            type: 'VARCHAR(100)',
            nullable: true,
            description: 'User first name',
          },
          {
            name: 'last_name',
            type: 'VARCHAR(100)',
            nullable: true,
            description: 'User last name',
          },
          {
            name: 'created_at',
            type: 'TIMESTAMP',
            nullable: false,
            description: 'Creation timestamp',
          },
          {
            name: 'updated_at',
            type: 'TIMESTAMP',
            nullable: false,
            description: 'Last update timestamp',
          },
        ],
        indexes: [
          { name: 'users_pkey', type: 'primary', columns: ['id'] },
          { name: 'users_email_idx', type: 'secondary', columns: ['email'] },
          {
            name: 'users_created_at_idx',
            type: 'secondary',
            columns: ['created_at'],
          },
        ],
        primaryKey: 'id',
      },
      {
        name: 'user_sessions',
        columns: [
          {
            name: 'id',
            type: 'UUID',
            nullable: false,
            description: 'Session ID',
          },
          {
            name: 'user_id',
            type: 'UUID',
            nullable: false,
            description: 'Foreign key to users',
          },
          {
            name: 'token',
            type: 'VARCHAR(500)',
            nullable: false,
            description: 'JWT token',
          },
          {
            name: 'expires_at',
            type: 'TIMESTAMP',
            nullable: false,
            description: 'Token expiration',
          },
          {
            name: 'created_at',
            type: 'TIMESTAMP',
            nullable: false,
            description: 'Session creation',
          },
        ],
        indexes: [
          { name: 'user_sessions_pkey', type: 'primary', columns: ['id'] },
          {
            name: 'user_sessions_user_id_idx',
            type: 'secondary',
            columns: ['user_id'],
          },
          {
            name: 'user_sessions_token_idx',
            type: 'secondary',
            columns: ['token'],
          },
        ],
        primaryKey: 'id',
      },
    ],
  },
  {
    id: '2',
    name: 'analytics_collection',
    type: 'collection',
    environment: 'production',
    lastScanned: '2024-01-14T15:45:00Z',
    columns: [
      {
        name: '_id',
        type: 'ObjectId',
        nullable: false,
        description: 'MongoDB document ID',
      },
      {
        name: 'user_id',
        type: 'String',
        nullable: false,
        description: 'User identifier',
      },
      {
        name: 'event_type',
        type: 'String',
        nullable: false,
        description: 'Type of analytics event',
      },
      {
        name: 'event_data',
        type: 'Object',
        nullable: true,
        description: 'Event payload data',
      },
      {
        name: 'timestamp',
        type: 'Date',
        nullable: false,
        description: 'Event timestamp',
      },
    ],
    indexes: [
      { name: '_id_', type: 'primary', columns: ['_id'] },
      { name: 'user_id_1', type: 'secondary', columns: ['user_id'] },
      { name: 'event_type_1', type: 'secondary', columns: ['event_type'] },
      { name: 'timestamp_1', type: 'secondary', columns: ['timestamp'] },
    ],
  },
]

export const mockFixtures = [
  {
    id: '1',
    name: 'User Creation Request',
    endpoint: '/api/v1/users',
    method: 'POST',
    type: 'request',
    content: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      password: 'SecurePass123!',
      role: 'user',
      preferences: {
        notifications: true,
        theme: 'light',
      },
    },
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    name: 'User Creation Response',
    endpoint: '/api/v1/users',
    method: 'POST',
    type: 'response',
    content: {
      id: '123e4567-e89b-12d3-a456-426614174000',
      name: 'John Doe',
      email: 'john.doe@example.com',
      role: 'user',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:30:00Z',
      preferences: {
        notifications: true,
        theme: 'light',
      },
    },
    lastUpdated: '2024-01-15T10:30:00Z',
  },
  {
    id: '3',
    name: 'User List Request',
    endpoint: '/api/v1/users',
    method: 'GET',
    type: 'request',
    content: {
      page: 1,
      limit: 20,
      sort: 'createdAt',
      order: 'desc',
      filter: {
        role: 'user',
        status: 'active',
      },
    },
    lastUpdated: '2024-01-14T15:45:00Z',
  },
  {
    id: '4',
    name: 'User List Response',
    endpoint: '/api/v1/users',
    method: 'GET',
    type: 'response',
    content: {
      data: [
        {
          id: '123e4567-e89b-12d3-a456-426614174000',
          name: 'John Doe',
          email: 'john.doe@example.com',
          role: 'user',
          status: 'active',
          createdAt: '2024-01-15T10:30:00Z',
        },
        {
          id: '456e7890-e89b-12d3-a456-426614174001',
          name: 'Jane Smith',
          email: 'jane.smith@example.com',
          role: 'admin',
          status: 'active',
          createdAt: '2024-01-14T15:45:00Z',
        },
      ],
      pagination: {
        page: 1,
        limit: 20,
        total: 2,
        totalPages: 1,
      },
    },
    lastUpdated: '2024-01-14T15:45:00Z',
  },
]

export const mockEventsMessages = [
  {
    id: '1',
    name: 'user.created',
    direction: 'emits',
    topic: 'user-events',
    stream: null,
    version: 'v1.0',
    description: 'Emitted when a new user is created',
    schema: {
      type: 'object',
      properties: {
        user_id: { type: 'string', description: 'User ID' },
        email: { type: 'string', description: 'User email' },
        created_at: {
          type: 'string',
          format: 'date-time',
          description: 'Creation timestamp',
        },
      },
      required: ['user_id', 'email', 'created_at'],
    },
    examplePayload: {
      user_id: '123e4567-e89b-12d3-a456-426614174000',
      email: 'john.doe@example.com',
      created_at: '2024-01-15T10:30:00Z',
    },
    deliverySemantics: 'at-least-once',
  },
  {
    id: '2',
    name: 'user.updated',
    direction: 'emits',
    topic: 'user-events',
    stream: null,
    version: 'v1.0',
    description: 'Emitted when user data is updated',
    schema: {
      type: 'object',
      properties: {
        user_id: { type: 'string', description: 'User ID' },
        changes: { type: 'object', description: 'Changed fields' },
        updated_at: {
          type: 'string',
          format: 'date-time',
          description: 'Update timestamp',
        },
      },
      required: ['user_id', 'changes', 'updated_at'],
    },
    examplePayload: {
      user_id: '123e4567-e89b-12d3-a456-426614174000',
      changes: { first_name: 'John', last_name: 'Doe' },
      updated_at: '2024-01-15T11:30:00Z',
    },
    deliverySemantics: 'at-least-once',
  },
  {
    id: '3',
    name: 'notification.send',
    direction: 'consumes',
    topic: 'notifications',
    stream: null,
    version: 'v1.0',
    description: 'Consumes notification requests',
    schema: {
      type: 'object',
      properties: {
        user_id: { type: 'string', description: 'Target user ID' },
        type: {
          type: 'string',
          enum: ['email', 'sms', 'push'],
          description: 'Notification type',
        },
        message: { type: 'string', description: 'Notification message' },
        priority: {
          type: 'string',
          enum: ['low', 'medium', 'high'],
          description: 'Message priority',
        },
      },
      required: ['user_id', 'type', 'message'],
    },
    examplePayload: {
      user_id: '123e4567-e89b-12d3-a456-426614174000',
      type: 'email',
      message: 'Welcome to our platform!',
      priority: 'medium',
    },
    deliverySemantics: 'exactly-once',
  },
  {
    id: '4',
    name: 'analytics.event',
    direction: 'emits',
    topic: null,
    stream: 'analytics-stream',
    version: 'v1.1',
    description: 'Emitted for analytics tracking',
    schema: {
      type: 'object',
      properties: {
        event_type: { type: 'string', description: 'Type of analytics event' },
        user_id: { type: 'string', description: 'User ID' },
        properties: { type: 'object', description: 'Event properties' },
        timestamp: {
          type: 'string',
          format: 'date-time',
          description: 'Event timestamp',
        },
      },
      required: ['event_type', 'user_id', 'timestamp'],
    },
    examplePayload: {
      event_type: 'page_view',
      user_id: '123e4567-e89b-12d3-a456-426614174000',
      properties: { page: '/dashboard', duration: 120 },
      timestamp: '2024-01-15T10:30:00Z',
    },
    deliverySemantics: 'at-most-once',
  },
]

export const mockFlowDiagrams: ServiceDiagram[] = [
  {
    id: '1',
    name: 'User Authentication Flow',
    type: 'flow',
    version: 'v1.2',
    lastUpdated: '2024-01-15T10:30:00Z',
    nodes: [
      {
        id: 'start',
        type: 'decision',
        label: 'User Login Request',
        position: { x: 100, y: 100 },
        linkedEndpoint: '/api/v1/auth/login',
      },
      {
        id: 'validate',
        type: 'api-call',
        label: 'Validate Credentials',
        position: { x: 300, y: 100 },
        linkedEndpoint: '/api/v1/auth/validate',
      },
      {
        id: 'generate-token',
        type: 'api-call',
        label: 'Generate JWT Token',
        position: { x: 500, y: 100 },
        linkedEndpoint: '/api/v1/auth/token',
      },
      {
        id: 'end',
        type: 'decision',
        label: 'Return Token',
        position: { x: 700, y: 100 },
        linkedEndpoint: '/api/v1/auth/login',
      },
    ],
    edges: [
      { id: 'e1', source: 'start', target: 'validate' },
      { id: 'e2', source: 'validate', target: 'generate-token' },
      { id: 'e3', source: 'generate-token', target: 'end' },
    ],
  },
  {
    id: '2',
    name: 'User Registration Flow',
    type: 'flow',
    version: 'v1.1',
    lastUpdated: '2024-01-14T15:45:00Z',
    nodes: [
      {
        id: 'start',
        type: 'decision',
        label: 'Registration Request',
        position: { x: 100, y: 100 },
        linkedEndpoint: '/api/v1/users',
      },
      {
        id: 'validate',
        type: 'api-call',
        label: 'Validate Input',
        position: { x: 300, y: 100 },
        linkedEndpoint: '/api/v1/users/validate',
      },
      {
        id: 'create-user',
        type: 'db-op',
        label: 'Create User Record',
        position: { x: 500, y: 100 },
        linkedSchema: 'users_table',
      },
      {
        id: 'send-email',
        type: 'external',
        label: 'Send Welcome Email',
        position: { x: 700, y: 100 },
        linkedJob: 'send-welcome-email',
      },
    ],
    edges: [
      { id: 'e1', source: 'start', target: 'validate' },
      { id: 'e2', source: 'validate', target: 'create-user' },
      { id: 'e3', source: 'create-user', target: 'send-email' },
    ],
  },
]

export const mockRunbooks = [
  {
    id: '1',
    title: 'User Service Deployment Guide',
    type: 'runbook',
    description:
      'Step-by-step guide for deploying the user service to production',
    lastReviewed: '2024-01-15T10:30:00Z',
    reviewer: 'John Doe',
    status: 'current',
    url: 'https://docs.example.com/runbooks/user-service-deployment',
    tags: ['deployment', 'production'],
  },
  {
    id: '2',
    title: 'Database Migration Procedures',
    type: 'runbook',
    description: 'Procedures for safely migrating user database schemas',
    lastReviewed: '2024-01-14T15:45:00Z',
    reviewer: 'Jane Smith',
    status: 'current',
    url: 'https://docs.example.com/runbooks/database-migration',
    tags: ['database', 'migration'],
  },
  {
    id: '3',
    title: 'Incident Response Playbook',
    type: 'playbook',
    description: 'Emergency procedures for user service incidents',
    lastReviewed: '2024-01-13T09:20:00Z',
    reviewer: 'Mike Johnson',
    status: 'current',
    url: 'https://docs.example.com/playbooks/incident-response',
    tags: ['incident', 'emergency'],
  },
  {
    id: '4',
    title: 'Performance Troubleshooting',
    type: 'runbook',
    description: 'Guide for diagnosing and fixing performance issues',
    lastReviewed: '2024-01-10T14:10:00Z',
    reviewer: 'Sarah Wilson',
    status: 'outdated',
    url: 'https://docs.example.com/runbooks/performance-troubleshooting',
    tags: ['performance', 'troubleshooting'],
  },
  {
    id: '5',
    title: 'Security Incident Response',
    type: 'playbook',
    description: 'Security incident response procedures and contacts',
    lastReviewed: '2024-01-12T11:30:00Z',
    reviewer: 'Alex Chen',
    status: 'current',
    url: 'https://docs.example.com/playbooks/security-incident',
    tags: ['security', 'incident'],
  },
]

export const mockNativeDocs = [
  {
    id: '1',
    title: 'API Documentation',
    type: 'native',
    description: 'Comprehensive API documentation for all endpoints',
    lastUpdated: '2024-01-15T10:30:00Z',
    content:
      '# User Service API\n\nThis service provides user management functionality...',
  },
  {
    id: '2',
    title: 'Architecture Overview',
    type: 'native',
    description: 'High-level architecture and design decisions',
    lastUpdated: '2024-01-14T15:45:00Z',
    content:
      '# User Service Architecture\n\nThe user service follows a microservices architecture...',
  },
  {
    id: '3',
    title: 'Development Setup',
    type: 'native',
    description: 'Local development environment setup guide',
    lastUpdated: '2024-01-13T09:20:00Z',
    content: '# Development Setup\n\nTo set up the user service locally...',
  },
]

export const mockTestCases = [
  {
    id: '1',
    title: 'User Creation - Valid Input',
    endpoint: '/api/v1/users',
    method: 'POST',
    tags: ['Auth', 'Validation'],
    lastUpdated: '2024-01-15T10:30:00Z',
    externalTest: 'https://test.example.com/user-creation',
    status: 'passing',
    description: 'Test user creation with valid input data',
    given: 'A valid user registration request',
    when: 'POST request is sent to /api/v1/users',
    then: 'User should be created and 201 status returned',
    inputs: {
      name: 'John Doe',
      email: 'john.doe@example.com',
      password: 'SecurePass123!',
    },
    expected: {
      status: 201,
      body: {
        id: 'string',
        name: 'John Doe',
        email: 'john.doe@example.com',
        role: 'user',
      },
    },
    observed: {
      status: 201,
      body: {
        id: '123e4567-e89b-12d3-a456-426614174000',
        name: 'John Doe',
        email: 'john.doe@example.com',
        role: 'user',
      },
    },
  },
  {
    id: '2',
    title: 'User Creation - Invalid Email',
    endpoint: '/api/v1/users',
    method: 'POST',
    tags: ['Validation'],
    lastUpdated: '2024-01-14T15:45:00Z',
    externalTest: null,
    status: 'passing',
    description: 'Test user creation with invalid email format',
    given: 'A user registration request with invalid email',
    when: 'POST request is sent to /api/v1/users',
    then: '400 status should be returned with validation error',
    inputs: {
      name: 'John Doe',
      email: 'invalid-email',
      password: 'SecurePass123!',
    },
    expected: {
      status: 400,
      body: {
        error: 'Invalid email format',
      },
    },
    observed: {
      status: 400,
      body: {
        error: 'Invalid email format',
      },
    },
  },
  {
    id: '3',
    title: 'User Authentication - Valid Credentials',
    endpoint: '/api/v1/auth/login',
    method: 'POST',
    tags: ['Auth'],
    lastUpdated: '2024-01-13T09:20:00Z',
    externalTest: 'https://test.example.com/auth-login',
    status: 'failing',
    description: 'Test user authentication with valid credentials',
    given: 'A user with valid credentials',
    when: 'POST request is sent to /api/v1/auth/login',
    then: 'JWT token should be returned',
    inputs: {
      email: 'john.doe@example.com',
      password: 'SecurePass123!',
    },
    expected: {
      status: 200,
      body: {
        token: 'string',
        refreshToken: 'string',
      },
    },
    observed: {
      status: 401,
      body: {
        error: 'Invalid credentials',
      },
    },
  },
]

export const mockAccessPatterns = [
  {
    id: '1',
    type: 'read',
    keyExpression: 'user_id = ? AND status = "active"',
    exampleQuery:
      'SELECT * FROM users WHERE user_id = "123" AND status = "active"',
    linkedEndpoints: ['/api/v1/users/{id}', '/api/v1/users/{id}/profile'],
    description: 'Get active user by ID',
    frequency: 'high',
    performance: 'fast',
  },
  {
    id: '2',
    type: 'write',
    keyExpression: 'user_id = ?',
    exampleQuery: 'UPDATE users SET last_login = NOW() WHERE user_id = "123"',
    linkedEndpoints: ['/api/v1/users/{id}', '/api/v1/auth/login'],
    description: 'Update user login timestamp',
    frequency: 'high',
    performance: 'fast',
  },
  {
    id: '3',
    type: 'read',
    keyExpression: 'email = ?',
    exampleQuery: 'SELECT * FROM users WHERE email = "user@example.com"',
    linkedEndpoints: ['/api/v1/auth/login', '/api/v1/users/search'],
    description: 'Find user by email address',
    frequency: 'medium',
    performance: 'fast',
  },
  {
    id: '4',
    type: 'read',
    keyExpression: 'created_at >= ? AND created_at <= ?',
    exampleQuery:
      'SELECT * FROM users WHERE created_at >= "2024-01-01" AND created_at <= "2024-01-31"',
    linkedEndpoints: ['/api/v1/users', '/api/v1/analytics/users'],
    description: 'Get users created in date range',
    frequency: 'low',
    performance: 'slow',
  },
  {
    id: '5',
    type: 'write',
    keyExpression: 'user_id = ? AND session_id = ?',
    exampleQuery:
      'INSERT INTO user_sessions (user_id, session_id, token, expires_at) VALUES (?, ?, ?, ?)',
    linkedEndpoints: ['/api/v1/auth/login', '/api/v1/auth/refresh'],
    description: 'Create new user session',
    frequency: 'high',
    performance: 'fast',
  },
]

export const mockBusinessLogicNotes = [
  {
    id: '1',
    title: 'User Authentication Flow',
    content: `This endpoint handles the complete user authentication flow including:

1. **Input Validation**: Email and password are validated against our security requirements
2. **Rate Limiting**: Maximum 5 attempts per minute per IP
3. **Password Hashing**: Uses bcrypt with salt rounds of 12
4. **JWT Generation**: Creates access and refresh tokens
5. **Audit Logging**: All authentication attempts are logged

**Security Considerations**:
- Passwords must be at least 8 characters with mixed case and numbers
- Failed attempts trigger progressive delays
- Tokens expire after 1 hour (access) and 30 days (refresh)`,
    linkedEndpoints: ['/api/v1/auth/login', '/api/v1/auth/refresh'],
    linkedDiagramNodes: [
      'auth-flow-start',
      'password-validation',
      'jwt-generation',
    ],
    lastUpdated: '2024-01-15T10:30:00Z',
    author: 'John Doe',
  },
  {
    id: '2',
    title: 'User Profile Update Logic',
    content: `The user profile update process includes several validation steps:

**Business Rules**:
- Email changes require verification
- Phone number updates trigger SMS verification
- Profile picture uploads are processed through our CDN
- Sensitive fields (SSN, etc.) require additional authentication

**Data Flow**:
1. Validate input data
2. Check permissions
3. Update database
4. Send notifications
5. Update search index`,
    linkedEndpoints: ['/api/v1/users/{id}', '/api/v1/users/{id}/verify-email'],
    linkedDiagramNodes: ['profile-update', 'email-verification'],
    lastUpdated: '2024-01-14T15:45:00Z',
    author: 'Jane Smith',
  },
  {
    id: '3',
    title: 'Payment Processing Workflow',
    content: `Complex payment processing with multiple providers:

**Provider Selection**:
- Primary: Stripe (for cards)
- Fallback: PayPal (for alternative payments)
- International: Adyen (for global coverage)

**Error Handling**:
- Network timeouts: 30 seconds
- Retry logic: 3 attempts with exponential backoff
- Fraud detection: Real-time scoring
- Compliance: PCI DSS Level 1`,
    linkedEndpoints: ['/api/v1/payments', '/api/v1/payments/{id}/status'],
    linkedDiagramNodes: ['payment-start', 'provider-selection', 'fraud-check'],
    lastUpdated: '2024-01-13T09:20:00Z',
    author: 'Mike Johnson',
  },
]

export const mockComments: ServiceComment[] = [
  {
    id: '1',
    content:
      'This endpoint needs better error handling for invalid user IDs. Consider adding validation middleware.',
    author: 'Jane Smith',
    createdAt: '2024-01-15T10:30:00Z',
    targetType: 'endpoint',
    targetId: '/api/v1/users/{id}',
    resolved: false,
    replies: [
      {
        id: '1-1',
        content: "Good point! I'll add input validation in the next PR.",
        author: 'John Doe',
        createdAt: '2024-01-15T11:00:00Z',
        targetType: 'endpoint',
        targetId: '/api/v1/users/{id}',
        resolved: false,
      },
    ],
  },
  {
    id: '2',
    content:
      'The database connection pool might be too small for production load. Consider increasing the pool size.',
    author: 'Mike Johnson',
    createdAt: '2024-01-14T15:45:00Z',
    targetType: 'schema',
    targetId: 'users_db',
    resolved: true,
    replies: [],
  },
  {
    id: '3',
    content:
      'This flow diagram is missing the error handling path. Should we add a decision node for validation failures?',
    author: 'Sarah Wilson',
    createdAt: '2024-01-13T09:20:00Z',
    targetType: 'diagram',
    targetId: 'user-auth-flow',
    resolved: false,
    replies: [
      {
        id: '3-1',
        content:
          "Yes, that would make the flow more complete. I'll update the diagram.",
        author: 'John Doe',
        createdAt: '2024-01-13T10:00:00Z',
        targetType: 'diagram',
        targetId: 'user-auth-flow',
        resolved: false,
      },
    ],
  },
  {
    id: '4',
    content:
      'The job cleanup process should run more frequently to prevent session table bloat.',
    author: 'Alex Chen',
    createdAt: '2024-01-12T14:10:00Z',
    targetType: 'job',
    targetId: 'cleanup-expired-sessions',
    resolved: false,
    replies: [],
  },
]

export const mockJobs: ServiceJob[] = [
  {
    id: '1',
    name: 'send-welcome-email',
    type: 'event',
    trigger: 'user.created',
    sourceFile: 'jobs/welcome-email.ts',
    lastUpdated: '2024-01-15T10:30:00Z',
    linkedFlowNode: 'send-email',
  },
  {
    id: '2',
    name: 'cleanup-expired-sessions',
    type: 'cron',
    trigger: '0 2 * * *',
    sourceFile: 'jobs/session-cleanup.ts',
    lastUpdated: '2024-01-14T15:45:00Z',
    linkedFlowNode: 'session-cleanup',
  },
  {
    id: '3',
    name: 'process-analytics-batch',
    type: 'queue',
    trigger: 'analytics.batch.process',
    sourceFile: 'jobs/analytics-processor.ts',
    lastUpdated: '2024-01-13T09:20:00Z',
    linkedFlowNode: 'analytics-processing',
  },
  {
    id: '4',
    name: 'backup-user-data',
    type: 'cron',
    trigger: '0 3 * * 0',
    sourceFile: 'jobs/backup.ts',
    lastUpdated: '2024-01-12T14:10:00Z',
    linkedFlowNode: 'data-backup',
  },
  {
    id: '5',
    name: 'send-notification',
    type: 'event',
    trigger: 'notification.send',
    sourceFile: 'jobs/notification-sender.ts',
    lastUpdated: '2024-01-11T11:30:00Z',
    linkedFlowNode: 'notification-send',
  },
]

export const mockDependencies = {
  inbound: [
    {
      id: '1',
      name: 'API Gateway',
      protocol: 'REST',
      endpoints: ['/api/v1/users/*'],
      status: 'healthy',
    },
    {
      id: '2',
      name: 'Load Balancer',
      protocol: 'HTTP',
      endpoints: ['*'],
      status: 'healthy',
    },
    {
      id: '3',
      name: 'Auth Service',
      protocol: 'REST',
      endpoints: ['/api/v1/auth/validate'],
      status: 'healthy',
    },
  ],
  outbound: [
    {
      id: '4',
      name: 'Database',
      protocol: 'SQL',
      endpoints: ['users', 'sessions'],
      status: 'healthy',
    },
    {
      id: '5',
      name: 'Email Service',
      protocol: 'REST',
      endpoints: ['/api/v1/emails/send'],
      status: 'healthy',
    },
    {
      id: '6',
      name: 'Notification Queue',
      protocol: 'Event',
      endpoints: ['user.notifications'],
      status: 'degraded',
    },
    {
      id: '7',
      name: 'Analytics Service',
      protocol: 'gRPC',
      endpoints: ['analytics.UserService'],
      status: 'healthy',
    },
  ],
}

export const mockConfigs: ServiceConfig[] = [
  {
    key: 'DATABASE_URL',
    description: 'Primary database connection string',
    tags: ['database', 'critical'],
    environments: {
      production: 'postgresql://user:pass@prod-db:5432/users',
      staging: 'postgresql://user:pass@staging-db:5432/users',
      development: 'postgresql://user:pass@dev-db:5432/users',
    },
    usedBy: ['/api/v1/users', '/api/v1/auth', 'user-service'],
  },
  {
    key: 'JWT_SECRET',
    description: 'Secret key for JWT token signing',
    tags: ['security', 'critical'],
    environments: {
      production: 'super-secret-prod-key-12345',
      staging: 'super-secret-staging-key-12345',
      development: 'super-secret-dev-key-12345',
    },
    usedBy: ['/api/v1/auth/login', '/api/v1/auth/refresh'],
  },
  {
    key: 'REDIS_URL',
    description: 'Redis connection for caching and sessions',
    tags: ['cache', 'sessions'],
    environments: {
      production: 'redis://prod-redis:6379',
      staging: 'redis://staging-redis:6379',
      development: 'redis://dev-redis:6379',
    },
    usedBy: ['session-cleanup', 'user-cache'],
  },
  {
    key: 'EMAIL_SERVICE_URL',
    description: 'External email service endpoint',
    tags: ['external', 'email'],
    environments: {
      production: 'https://email-api.prod.example.com',
      staging: 'https://email-api.staging.example.com',
      development: 'https://email-api.dev.example.com',
    },
    usedBy: ['send-welcome-email', 'send-notification'],
  },
  {
    key: 'FEATURE_FLAG_NEW_UI',
    description: 'Feature flag for new user interface',
    tags: ['feature-flag'],
    environments: {
      production: 'false',
      staging: 'true',
      development: 'true',
    },
    usedBy: ['/api/v1/users', 'user-frontend'],
  },
  {
    key: 'USER_PHONE_NUMBER',
    description: 'User phone number for notifications',
    tags: ['pii'],
    environments: {
      production: '+1234567890',
      staging: '+1234567890',
      development: '+1234567890',
    },
    usedBy: ['send-notification'],
  },
]

export const mockOwners: ServiceOwner[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'owner',
    team: 'Platform Team',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    role: 'contributor',
    team: 'Platform Team',
  },
  {
    id: '3',
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    role: 'reviewer',
    team: 'Security Team',
  },
  {
    id: '4',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@example.com',
    role: 'contributor',
    team: 'Platform Team',
  },
]

export const mockCollaborationInfo = {
  slackChannel: '#user-service',
  onCallLink: 'https://oncall.example.com/user-service',
  teamWiki: 'https://wiki.example.com/teams/platform',
  codeReviewers: ['jane.smith@example.com', 'mike.johnson@example.com'],
  escalationContacts: ['john.doe@example.com', 'team-lead@example.com'],
}
