export enum ComponentInputType {
  TextInput = 'Text Input',
  URLInput = 'URL Input',
  NumberInput = 'Number Input',
  TextBox = 'Text Editor',
  DatePicker = 'Date Picker',
  DropdownSelect = 'Dropdown',
  MultiSelect = 'Multi Select',
  BooleanToggle = 'Boolean Toggle',
  LinkOrFileUpload = 'Link or File Upload',
  RichTextEditor = 'Rich Text Editor',
  CodeEditor = 'Code Editor',
  KeyValueList = 'Key-Value List',
  TagInput = 'Tag Input',
  DateRangePicker = 'Date Range Picker',
  ColorPicker = 'Color Picker',
  Slider = 'Slider',
  FileUpload = 'File Upload',
  SearchSelect = 'Search Select',
  CheckboxGroup = 'Checkbox Group',
}
