// DO NOT EDIT THIS FILE!

import { signOut } from '@/store/auth-store'
import {
  useAuthStore,
  useCurrentOrganization,
} from '@/store/auth-store/use-auth-store'
import { PropsWithChildren } from 'react'
import { Navigate } from 'react-router-dom'

export function AuthenticatedGuard({ children }: PropsWithChildren) {
  const status = useAuthStore((state) => state.status)
  const user = useAuthStore((state) => state.user)

  if (status === 'loading') {
    return <div>Loading...</div>
  }

  if (status === 'authenticated') {
    if (user) return children

    void signOut()
  }

  return <Navigate to="/sign-in" replace />
}

export function UnauthenticatedGuard({ children }: PropsWithChildren) {
  const status = useAuthStore((state) => state.status)

  if (status === 'authenticated') {
    return <Navigate to="/" replace />
  }

  return children
}

export function MustHaveOrganizationGuard({ children }: PropsWithChildren) {
  const organizations = useAuthStore((state) => state.organizations)
  const resolvedOrganization = useCurrentOrganization()

  if (organizations.length === 0) {
    return <Navigate to="/onboarding" replace />
  }

  if (!resolvedOrganization) {
    return <Navigate to="/" replace />
  }

  return <>{children}</>
}

export function MustBeServerAdminGuard({ children }: PropsWithChildren) {
  const isAdmin = useAuthStore((state) => state.user?.role === 'admin')
  if (!isAdmin) {
    return <Navigate to="/" replace />
  }

  return <>{children}</>
}
